const OUTFIT_DATA = {
  "1": {"name": "ID 1", "type": "monster"},
  "2": {"name": "Bibby Bloodbath", "type": "monster"},
  "3": {"name": "War Wolf", "type": "monster"},
  "4": {"name": "Orc Rider", "type": "monster"},
  "5": {"name": "Orc", "type": "monster"},
  "6": {"name": "Kraknaknork", "type": "monster"},
  "7": {"name": "Scar Tribe Warrior", "type": "monster"},
  "8": {"name": "Hacker", "type": "monster"},
  "9": {"name": "Acolyte of Darkness", "type": "monster"},
  "10": {"name": "Yellow Butterfly", "type": "monster"},
  "11": {"name": "Massive Water Elemental", "type": "monster"},
  "12": {"name": "Apocalypse", "type": "monster"},
  "13": {"name": "Black Sheep", "type": "monster"},
  "14": {"name": "Evil Sheep", "type": "monster"},
  "15": {"name": "Mountain Troll", "type": "monster"},
  "16": {"name": "Bear", "type": "monster"},
  "17": {"name": "Bonelord", "type": "monster"},
  "18": {"name": "Ghoul", "type": "monster"},
  "19": {"name": "Strange Slime", "type": "monster"},
  "20": {"name": "Quara Predator", "type": "monster"},
  "21": {"name": "Rat", "type": "monster"},
  "22": {"name": "Juvenile Cyclops", "type": "monster"},
  "23": {"name": "Apprentice Sheng", "type": "monster"},
  "24": {"name": "Minotaur Archer", "type": "monster"},
  "25": {"name": "Minotaur", "type": "monster"},
  "26": {"name": "Animated Rotworm", "type": "monster"},
  "27": {"name": "Starving Wolf", "type": "monster"},
  "28": {"name": "Sacred Snake", "type": "monster"},
  "29": {"name": "Minotaur Cult Zealot", "type": "monster"},
  "30": {"name": "Spider", "type": "monster"},
  "31": {"name": "Deer", "type": "monster"},
  "32": {"name": "Dog", "type": "monster"},
  "33": {"name": "Brittle Skeleton", "type": "monster"},
  "34": {"name": "Glitterscale", "type": "monster"},
  "35": {"name": "Bazir", "type": "monster"},
  "36": {"name": "Poison Spider", "type": "monster"},
  "37": {"name": "Undead Minion", "type": "monster"},
  "38": {"name": "Cave Spider", "type": "monster"},
  "39": {"name": "Dragon Lord", "type": "monster"},
  "40": {"name": "Lesser Fire Devil", "type": "monster"},
  "41": {"name": "Lion", "type": "monster"},
  "42": {"name": "Polar Bear", "type": "monster"},
  "43": {"name": "Dawn Scorpion", "type": "monster"},
  "44": {"name": "Willi Wasp", "type": "monster"},
  "45": {"name": "Bug", "type": "monster"},
  "46": {"name": "Quara Constrictor", "type": "monster"},
  "47": {"name": "Quara Hydromancer", "type": "monster"},
  "48": {"name": "Rift Phantom", "type": "monster"},
  "49": {"name": "Fire Elemental", "type": "monster"},
  "50": {"name": "Orc Spearman", "type": "monster"},
  "51": {"name": "Green Djinn", "type": "monster"},
  "52": {"name": "Winter Wolf", "type": "monster"},
  "53": {"name": "Frost Troll", "type": "monster"},
  "54": {"name": "Ekatrix", "type": "monster"},
  "55": {"name": "Behemoth", "type": "monster"},
  "56": {"name": "Munster", "type": "monster"},
  "57": {"name": "Monk", "type": "monster"},
  "58": {"name": "Priestess", "type": "monster"},
  "59": {"name": "Renegade Orc", "type": "monster"},
  "60": {"name": "Mushroom Sniffer", "type": "monster"},
  "61": {"name": "Muglex Clan Footman", "type": "monster"},
  "62": {"name": "Elf", "type": "monster"},
  "63": {"name": "Memory of an Elf", "type": "monster"},
  "64": {"name": "Mornenion", "type": "monster"},
  "65": {"name": "Animated Mummy", "type": "monster"},
  "66": {"name": "Mad Technomancer", "type": "monster"},
  "67": {"name": "Stone Golem", "type": "monster"},
  "68": {"name": "Armenius (Creature)", "type": "monster"},
  "69": {"name": "Crazed Dwarf", "type": "monster"},
  "70": {"name": "Elvira Hammerthrust", "type": "monster"},
  "71": {"name": "Dwarf Soldier", "type": "monster"},
  "72": {"name": "Quara Mantassin", "type": "monster"},
  "73": {"name": "Memory of a Hero", "type": "monster"},
  "74": {"name": "The Halloween Hare", "type": "monster"},
  "75": {"name": "ID 75", "type": "monster"},
  "76": {"name": "Swamp Troll", "type": "monster"},
  "77": {"name": "Quara Pincher", "type": "monster"},
  "78": {"name": "Memory of a Banshee", "type": "monster"},
  "79": {"name": "Memory of a Scarab", "type": "monster"},
  "80": {"name": "Blue Djinn", "type": "monster"},
  "81": {"name": "Black Cobra", "type": "monster"},
  "82": {"name": "Brain Parasite", "type": "monster"},
  "83": {"name": "Burrowing Beetle", "type": "monster"},
  "84": {"name": "Morguthis", "type": "monster"},
  "85": {"name": "Vashresamun", "type": "monster"},
  "86": {"name": "Mahrdis", "type": "monster"},
  "87": {"name": "Dipthrah", "type": "monster"},
  "88": {"name": "Rahemos", "type": "monster"},
  "89": {"name": "Thalas", "type": "monster"},
  "90": {"name": "Omruc", "type": "monster"},
  "91": {"name": "Ashmunrah", "type": "monster"},
  "92": {"name": "Mimic", "type": "monster"},
  "93": {"name": "Pirate Marauder", "type": "monster"},
  "94": {"name": "Ghoulish Hyaena", "type": "monster"},
  "95": {"name": "Gargoyle", "type": "monster"},
  "96": {"name": "Pirate Cutthroat", "type": "monster"},
  "97": {"name": "Memory of a Pirate", "type": "monster"},
  "98": {"name": "Pirate Corsair", "type": "monster"},
  "99": {"name": "Gravelord Oshuran", "type": "monster"},
  "100": {"name": "Retainer of Baeloc", "type": "monster"},
  "101": {"name": "Ribstride", "type": "monster"},
  "102": {"name": "Whirling Blades", "type": "monster"},
  "103": {"name": "Efreet", "type": "monster"},
  "104": {"name": "Fahim the Wise", "type": "monster"},
  "105": {"name": "Badger", "type": "monster"},
  "106": {"name": "Skunk", "type": "monster"},
  "107": {"name": "ID 107", "type": "monster"},
  "108": {"name": "Elder Bonelord", "type": "monster"},
  "109": {"name": "Gazer", "type": "monster"},
  "110": {"name": "Yeti", "type": "monster"},
  "111": {"name": "Agressive Chicken", "type": "monster"},
  "112": {"name": "Crab", "type": "monster"},
  "113": {"name": "Fatality", "type": "monster"},
  "114": {"name": "Lizard Sentinel", "type": "monster"},
  "115": {"name": "Lizard Magistratus", "type": "monster"},
  "116": {"name": "Hairman the Huge", "type": "monster"},
  "117": {"name": "Merlkin", "type": "monster"},
  "118": {"name": "Sibang", "type": "monster"},
  "119": {"name": "The Snapper", "type": "monster"},
  "120": {"name": "Carniphila", "type": "monster"},
  "121": {"name": "Hydra", "type": "monster"},
  "122": {"name": "Dawn Bat", "type": "monster"},
  "123": {"name": "Panda", "type": "monster"},
  "124": {"name": "Centipede", "type": "monster"},
  "125": {"name": "Tiger", "type": "monster"},
  "126": {"name": "ID 126", "type": "monster"},
  "127": {"name": "ID 127", "type": "monster"},
  "128": {"name": "Citizen", "type": "male"},
  "129": {"name": "Hunter", "type": "male"},
  "130": {"name": "Mage", "type": "male"},
  "131": {"name": "Knight", "type": "male"},
  "132": {"name": "Nobleman", "type": "male"},
  "133": {"name": "Summoner", "type": "male"},
  "134": {"name": "Warrior", "type": "male"},
  "135": {"name": "ID 135", "type": "monster"},
  "136": {"name": "Citizen", "type": "female"},
  "137": {"name": "Hunter", "type": "female"},
  "138": {"name": "Mage", "type": "female"},
  "139": {"name": "Knight", "type": "female"},
  "140": {"name": "Noblewoman", "type": "female"},
  "141": {"name": "Summoner", "type": "female"},
  "142": {"name": "Warrior", "type": "female"},
  "143": {"name": "Barbarian", "type": "male"},
  "144": {"name": "Druid", "type": "male"},
  "145": {"name": "Wizard", "type": "male"},
  "146": {"name": "Oriental", "type": "male"},
  "147": {"name": "Barbarian", "type": "female"},
  "148": {"name": "Druid", "type": "female"},
  "149": {"name": "Wizard", "type": "female"},
  "150": {"name": "Oriental", "type": "female"},
  "151": {"name": "Pirate", "type": "male"},
  "152": {"name": "Assassin", "type": "male"},
  "153": {"name": "Beggar", "type": "male"},
  "154": {"name": "Shaman", "type": "male"},
  "155": {"name": "Pirate", "type": "female"},
  "156": {"name": "Assassin", "type": "female"},
  "157": {"name": "Beggar", "type": "female"},
  "158": {"name": "Shaman", "type": "female"},
  "159": {"name": "Elf Overseer", "type": "monster"},
  "160": {"name": "Dwarf Henchman", "type": "monster"},
  "161": {"name": "ID 161", "type": "monster"},
  "162": {"name": "ID 162", "type": "monster"},
  "163": {"name": "ID 163", "type": "monster"},
  "164": {"name": "ID 164", "type": "monster"},
  "165": {"name": "ID 165", "type": "monster"},
  "166": {"name": "ID 166", "type": "monster"},
  "167": {"name": "ID 167", "type": "monster"},
  "168": {"name": "ID 168", "type": "monster"},
  "169": {"name": "ID 169", "type": "monster"},
  "170": {"name": "ID 170", "type": "monster"},
  "171": {"name": "ID 171", "type": "monster"},
  "172": {"name": "ID 172", "type": "monster"},
  "173": {"name": "ID 173", "type": "monster"},
  "174": {"name": "ID 174", "type": "monster"},
  "175": {"name": "ID 175", "type": "monster"},
  "176": {"name": "ID 176", "type": "monster"},
  "177": {"name": "ID 177", "type": "monster"},
  "178": {"name": "ID 178", "type": "monster"},
  "179": {"name": "ID 179", "type": "monster"},
  "180": {"name": "ID 180", "type": "monster"},
  "181": {"name": "ID 181", "type": "monster"},
  "182": {"name": "ID 182", "type": "monster"},
  "183": {"name": "ID 183", "type": "monster"},
  "184": {"name": "ID 184", "type": "monster"},
  "185": {"name": "ID 185", "type": "monster"},
  "186": {"name": "ID 186", "type": "monster"},
  "187": {"name": "ID 187", "type": "monster"},
  "188": {"name": "ID 188", "type": "monster"},
  "189": {"name": "ID 189", "type": "monster"},
  "190": {"name": "ID 190", "type": "monster"},
  "191": {"name": "ID 191", "type": "monster"},
  "192": {"name": "Carrion Worm", "type": "monster"},
  "193": {"name": "Grandfather Tridian", "type": "monster"},
  "194": {"name": "Acolyte of the Cult", "type": "monster"},
  "195": {"name": "Spectral Scum", "type": "monster"},
  "196": {"name": "Captain Jones", "type": "monster"},
  "197": {"name": "Tortoise", "type": "monster"},
  "198": {"name": "Thornback Tortoise", "type": "monster"},
  "199": {"name": "Memory of a Mammoth", "type": "monster"},
  "200": {"name": "Blood Crab", "type": "monster"},
  "201": {"name": "Orshabaal", "type": "monster"},
  "202": {"name": "The Horned Fox", "type": "monster"},
  "203": {"name": "Dharalion", "type": "monster"},
  "204": {"name": "Demodras", "type": "monster"},
  "205": {"name": "Grorlam", "type": "monster"},
  "206": {"name": "Fernfang", "type": "monster"},
  "207": {"name": "ID 207", "type": "monster"},
  "208": {"name": "The Old Widow", "type": "monster"},
  "209": {"name": "Necropharus", "type": "monster"},
  "210": {"name": "The Evil Eye", "type": "monster"},
  "211": {"name": "Elephant", "type": "monster"},
  "212": {"name": "Flamingo", "type": "monster"},
  "213": {"name": "ID 213", "type": "monster"},
  "214": {"name": "Dworc Voodoomaster", "type": "monster"},
  "215": {"name": "Dworc Fleshhunter", "type": "monster"},
  "216": {"name": "Dworc Venomsniper", "type": "monster"},
  "217": {"name": "Cave Parrot", "type": "monster"},
  "218": {"name": "Tame Terror Bird", "type": "monster"},
  "219": {"name": "Spider Queen", "type": "monster"},
  "220": {"name": "Srezz Yellow Eyes", "type": "monster"},
  "221": {"name": "Spit Nettle", "type": "monster"},
  "222": {"name": "Filth Toad", "type": "monster"},
  "223": {"name": "Seagull", "type": "monster"},
  "224": {"name": "Green Frog", "type": "monster"},
  "225": {"name": "Dark Monk", "type": "monster"},
  "226": {"name": "Azure Frog", "type": "monster"},
  "227": {"name": "Blue Butterfly", "type": "monster"},
  "228": {"name": "Red Butterfly", "type": "monster"},
  "229": {"name": "Ferumbras Mortal Shell", "type": "monster"},
  "230": {"name": "The Handmaiden", "type": "monster"},
  "231": {"name": "Pythius The Rotten", "type": "monster"},
  "232": {"name": "Damned Soul", "type": "monster"},
  "233": {"name": "Betrayed Wraith", "type": "monster"},
  "234": {"name": "Dark Torturer", "type": "monster"},
  "235": {"name": "Fetter", "type": "monster"},
  "236": {"name": "Destroyer", "type": "monster"},
  "237": {"name": "Diabolic Imp", "type": "monster"},
  "238": {"name": "Disgusting Ooze", "type": "monster"},
  "239": {"name": "Heoni", "type": "monster"},
  "240": {"name": "Hellhound", "type": "monster"},
  "241": {"name": "Phantasm", "type": "monster"},
  "242": {"name": "Massive Fire Elemental", "type": "monster"},
  "243": {"name": "Hellfire Fighter", "type": "monster"},
  "244": {"name": "Juggernaut", "type": "monster"},
  "245": {"name": "Nightmare", "type": "monster"},
  "246": {"name": "Unbound Blightwalker", "type": "monster"},
  "247": {"name": "Plaguesmith", "type": "monster"},
  "248": {"name": "Frost Dragon", "type": "monster"},
  "249": {"name": "Chakoya Tribewarden", "type": "monster"},
  "250": {"name": "Dire Penguin", "type": "monster"},
  "251": {"name": "Norseman", "type": "male"},
  "252": {"name": "Norsewoman", "type": "female"},
  "253": {"name": "Barbarian Headsplitter", "type": "monster"},
  "254": {"name": "Barbarian Skullhunter", "type": "monster"},
  "255": {"name": "Barbarian Bloodwalker", "type": "monster"},
  "256": {"name": "Braindeath", "type": "monster"},
  "257": {"name": "Frost Giant", "type": "monster"},
  "258": {"name": "Husky", "type": "monster"},
  "259": {"name": "Chakoya Toolshaper", "type": "monster"},
  "260": {"name": "Chakoya Windcaller", "type": "monster"},
  "261": {"name": "The Collector", "type": "monster"},
  "262": {"name": "Silver Rabbit", "type": "monster"},
  "263": {"name": "The Bloodweb", "type": "monster"},
  "264": {"name": "Barbarian Brutetamer", "type": "monster"},
  "265": {"name": "Frost Giantess", "type": "monster"},
  "266": {"name": "ID 266", "type": "monster"},
  "267": {"name": "ID 267", "type": "monster"},
  "268": {"name": "Nightmare", "type": "male"},
  "269": {"name": "Nightmare", "type": "female"},
  "270": {"name": "Jester", "type": "female"},
  "271": {"name": "Dragon Hatchling", "type": "monster"},
  "272": {"name": "Dragon Lord Hatchling", "type": "monster"},
  "273": {"name": "Jester", "type": "male"},
  "274": {"name": "Enraged Squirrel", "type": "monster"},
  "275": {"name": "Leviathan", "type": "monster"},
  "276": {"name": "Cat", "type": "monster"},
  "277": {"name": "Cyclops Smith", "type": "monster"},
  "278": {"name": "Brotherhood", "type": "male"},
  "279": {"name": "Brotherhood", "type": "female"},
  "280": {"name": "Cyclops Drone", "type": "monster"},
  "281": {"name": "Big Boss Trolliver", "type": "monster"},
  "282": {"name": "Island Troll", "type": "monster"},
  "283": {"name": "Frost Dragon Hatchling", "type": "monster"},
  "284": {"name": "Cockroach", "type": "monster"},
  "285": {"name": "Massive Earth Elemental", "type": "monster"},
  "286": {"name": "Water Elemental", "type": "monster"},
  "287": {"name": "Diblis the Fair", "type": "monster"},
  "288": {"name": "Demon Hunter", "type": "female"},
  "289": {"name": "Demon Hunter", "type": "male"},
  "290": {"name": "Massive Energy Elemental", "type": "monster"},
  "291": {"name": "Wyrm", "type": "monster"},
  "292": {"name": "The Mutated Pumpkin", "type": "monster"},
  "293": {"name": "Energy Elemental", "type": "monster"},
  "294": {"name": "Wisp", "type": "monster"},
  "295": {"name": "Versperoth", "type": "monster"},
  "296": {"name": "Muglex Clan Assassin", "type": "monster"},
  "297": {"name": "Muglex Clan Scavenger", "type": "monster"},
  "298": {"name": "Teleskor", "type": "monster"},
  "299": {"name": "Diseased Bill", "type": "monster"},
  "300": {"name": "Duskbringer", "type": "monster"},
  "301": {"name": "Earth Elemental", "type": "monster"},
  "302": {"name": "ID 302", "type": "monster"},
  "303": {"name": "ID 303", "type": "monster"},
  "304": {"name": "Damaged Worker Golem", "type": "monster"},
  "305": {"name": "Mutated Rat", "type": "monster"},
  "306": {"name": "Risen Soldier", "type": "monster"},
  "307": {"name": "Mutated Bat", "type": "monster"},
  "308": {"name": "Werewolf", "type": "monster"},
  "309": {"name": "Memory of a Yalahari", "type": "monster"},
  "310": {"name": "Bane Bringer", "type": "monster"},
  "311": {"name": "Zombie", "type": "monster"},
  "312": {"name": "Vampire Bride", "type": "monster"},
  "313": {"name": "Gozzler", "type": "monster"},
  "314": {"name": "Acid Blob", "type": "monster"},
  "315": {"name": "Essence of Darkness", "type": "monster"},
  "316": {"name": "Mercury Blob", "type": "monster"},
  "317": {"name": "Young Sea Serpent", "type": "monster"},
  "318": {"name": "Mutated Tiger", "type": "monster"},
  "319": {"name": "ID 319", "type": "monster"},
  "320": {"name": "Herald of Gloom", "type": "monster"},
  "321": {"name": "Nightmare Scion", "type": "monster"},
  "322": {"name": "Hellspawn", "type": "monster"},
  "323": {"name": "Mutated Human", "type": "monster"},
  "324": {"name": "Yalaharian", "type": "female"},
  "325": {"name": "Yalaharian", "type": "male"},
  "326": {"name": "War Golem", "type": "monster"},
  "327": {"name": "ID 327", "type": "monster"},
  "328": {"name": "Newly Wed", "type": "male"},
  "329": {"name": "Newly Wed", "type": "female"},
  "330": {"name": "Gorga", "type": "monster"},
  "331": {"name": "ID 331", "type": "monster"},
  "332": {"name": "ID 332", "type": "monster"},
  "333": {"name": "Clay Guardian", "type": "monster"},
  "334": {"name": "Draken Warmaster", "type": "monster"},
  "335": {"name": "Warmaster", "type": "male"},
  "336": {"name": "Warmaster", "type": "female"},
  "337": {"name": "Memory of a Lizard", "type": "monster"},
  "338": {"name": "Lizard Legionnaire", "type": "monster"},
  "339": {"name": "Lizard Dragon Priest", "type": "monster"},
  "340": {"name": "Draken Spellweaver", "type": "monster"},
  "341": {"name": "Gnarlhound", "type": "monster"},
  "342": {"name": "Clubarc The Plunderer", "type": "monster"},
  "343": {"name": "Fazzrah", "type": "monster"},
  "344": {"name": "The Voice of Ruin", "type": "monster"},
  "345": {"name": "Eternal Guardian", "type": "monster"},
  "346": {"name": "Terramite", "type": "monster"},
  "347": {"name": "Wailing Widow", "type": "monster"},
  "348": {"name": "The Blightfather", "type": "monster"},
  "349": {"name": "Vermin Swarm", "type": "monster"},
  "350": {"name": "Sandcrawler", "type": "monster"},
  "351": {"name": "Ghastly Dragon", "type": "monster"},
  "352": {"name": "Sulphur Scuttler", "type": "monster"},
  "353": {"name": "ID 353", "type": "monster"},
  "354": {"name": "ID 354", "type": "monster"},
  "355": {"name": "Lovely Souleater", "type": "monster"},
  "356": {"name": "Snake God Essence", "type": "monster"},
  "357": {"name": "Draken Abomination", "type": "monster"},
  "358": {"name": "Dreadmaw", "type": "monster"},
  "359": {"name": "ID 359", "type": "monster"},
  "360": {"name": "ID 360", "type": "monster"},
  "361": {"name": "Chikhaton", "type": "monster"},
  "362": {"name": "Draken Elite", "type": "monster"},
  "363": {"name": "ID 363", "type": "monster"},
  "364": {"name": "Lizard Abomination", "type": "monster"},
  "365": {"name": "ID 365", "type": "monster"},
  "366": {"name": "Wayfarer", "type": "female"},
  "367": {"name": "Wayfarer", "type": "male"},
  "368": {"name": "ID 368", "type": "monster"},
  "369": {"name": "ID 369", "type": "monster"},
  "370": {"name": "ID 370", "type": "monster"},
  "371": {"name": "ID 371", "type": "monster"},
  "372": {"name": "ID 372", "type": "monster"},
  "373": {"name": "ID 373", "type": "monster"},
  "374": {"name": "ID 374", "type": "monster"},
  "375": {"name": "ID 375", "type": "monster"},
  "376": {"name": "ID 376", "type": "monster"},
  "377": {"name": "ID 377", "type": "monster"},
  "378": {"name": "ID 378", "type": "monster"},
  "379": {"name": "ID 379", "type": "monster"},
  "380": {"name": "Boar", "type": "monster"},
  "381": {"name": "Tromphonyte", "type": "monster"},
  "382": {"name": "Draptor", "type": "monster"},
  "383": {"name": "Crustacea Gigantica", "type": "monster"},
  "384": {"name": "Bone Jaw", "type": "monster"},
  "385": {"name": "Midnight Panther", "type": "monster"},
  "386": {"name": "ID 386", "type": "monster"},
  "387": {"name": "Donkey", "type": "monster"},
  "388": {"name": "ID 388", "type": "monster"},
  "389": {"name": "ID 389", "type": "monster"},
  "390": {"name": "ID 390", "type": "monster"},
  "391": {"name": "Crystal Wolf", "type": "monster"},
  "392": {"name": "ID 392", "type": "monster"},
  "393": {"name": "Wild Horse", "type": "monster"},
  "394": {"name": "Mad Mage", "type": "monster"},
  "395": {"name": "Iron Servant", "type": "monster"},
  "396": {"name": "Golden Servant", "type": "monster"},
  "397": {"name": "Diamond Servant", "type": "monster"},
  "398": {"name": "Sandstone Scorpion", "type": "monster"},
  "399": {"name": "ID 399", "type": "monster"},
  "400": {"name": "Desperate White Deer", "type": "monster"},
  "401": {"name": "ID 401", "type": "monster"},
  "402": {"name": "ID 402", "type": "monster"},
  "403": {"name": "Memory of an Insectoid", "type": "monster"},
  "404": {"name": "Dromedary", "type": "monster"},
  "405": {"name": "ID 405", "type": "monster"},
  "406": {"name": "ID 406", "type": "monster"},
  "407": {"name": "Slug", "type": "monster"},
  "408": {"name": "Yielothax", "type": "monster"},
  "409": {"name": "Shaburak Lord", "type": "monster"},
  "410": {"name": "Askarak Lord", "type": "monster"},
  "411": {"name": "ID 411", "type": "monster"},
  "412": {"name": "Bog Frog", "type": "monster"},
  "413": {"name": "Deepling Scout", "type": "monster"},
  "414": {"name": "Thornfire Wolf", "type": "monster"},
  "415": {"name": "ID 415", "type": "monster"},
  "416": {"name": "Raging mage", "type": "monster"},
  "417": {"name": "Shaburak Demon", "type": "monster"},
  "418": {"name": "Shaburak Prince", "type": "monster"},
  "419": {"name": "Askarak Prince", "type": "monster"},
  "420": {"name": "Askarak Demon", "type": "monster"},
  "421": {"name": "ID 421", "type": "monster"},
  "422": {"name": "ID 422", "type": "monster"},
  "423": {"name": "Energized Raging Mage", "type": "monster"},
  "424": {"name": "ID 424", "type": "monster"},
  "425": {"name": "Feverish Citizen", "type": "monster"},
  "426": {"name": "ID 426", "type": "monster"},
  "427": {"name": "ID 427", "type": "monster"},
  "428": {"name": "ID 428", "type": "monster"},
  "429": {"name": "ID 429", "type": "monster"},
  "430": {"name": "Afflicted", "type": "male"},
  "431": {"name": "Afflicted", "type": "female"},
  "432": {"name": "Elementalist", "type": "male"},
  "433": {"name": "Elementalist", "type": "female"},
  "434": {"name": "Grey Horse", "type": "monster"},
  "435": {"name": "Horse", "type": "monster"},
  "436": {"name": "Brown Horse", "type": "monster"},
  "437": {"name": "ID 437", "type": "monster"},
  "438": {"name": "ID 438", "type": "monster"},
  "439": {"name": "ID 439", "type": "monster"},
  "440": {"name": "ID 440", "type": "monster"},
  "441": {"name": "Deepling Elite", "type": "monster"},
  "442": {"name": "Deepling Guard", "type": "monster"},
  "443": {"name": "Deepling Master Librarian", "type": "monster"},
  "444": {"name": "Jaul", "type": "monster"},
  "445": {"name": "Obujos", "type": "monster"},
  "446": {"name": "Tanjis", "type": "monster"},
  "447": {"name": "ID 447", "type": "monster"},
  "448": {"name": "Ladybug", "type": "monster"},
  "449": {"name": "Manta Ray", "type": "monster"},
  "450": {"name": "ID 450", "type": "monster"},
  "451": {"name": "Abyssal Calamary", "type": "monster"},
  "452": {"name": "Jellyfish", "type": "monster"},
  "453": {"name": "Shark", "type": "monster"},
  "454": {"name": "Northern Pike", "type": "monster"},
  "455": {"name": "Fish", "type": "monster"},
  "456": {"name": "Crawler", "type": "monster"},
  "457": {"name": "Fleshslicer", "type": "monster"},
  "458": {"name": "Hive Overseer", "type": "monster"},
  "459": {"name": "Floor Blob", "type": "monster"},
  "460": {"name": "Lesser Swarmer", "type": "monster"},
  "461": {"name": "Spitter", "type": "monster"},
  "462": {"name": "Waspoid", "type": "monster"},
  "463": {"name": "Deepling", "type": "male"},
  "464": {"name": "Deepling", "type": "female"},
  "465": {"name": "Insectoid", "type": "male"},
  "466": {"name": "Insectoid", "type": "female"},
  "467": {"name": "ID 467", "type": "monster"},
  "468": {"name": "ID 468", "type": "monster"},
  "469": {"name": "ID 469", "type": "monster"},
  "470": {"name": "Deepling Brawler", "type": "monster"},
  "471": {"name": "Entrepreneur", "type": "female"},
  "472": {"name": "Entrepreneur", "type": "male"},
  "473": {"name": "Poodle", "type": "monster"},
  "474": {"name": "ID 474", "type": "monster"},
  "475": {"name": "ID 475", "type": "monster"},
  "476": {"name": "ID 476", "type": "monster"},
  "477": {"name": "ID 477", "type": "monster"},
  "478": {"name": "ID 478", "type": "monster"},
  "479": {"name": "ID 479", "type": "monster"},
  "480": {"name": "ID 480", "type": "monster"},
  "481": {"name": "ID 481", "type": "monster"},
  "482": {"name": "ID 482", "type": "monster"},
  "483": {"name": "ID 483", "type": "monster"},
  "484": {"name": "ID 484", "type": "monster"},
  "485": {"name": "ID 485", "type": "monster"},
  "486": {"name": "Stone Devourer", "type": "monster"},
  "487": {"name": "Armadile", "type": "monster"},
  "488": {"name": "Memory of a Fungus", "type": "monster"},
  "489": {"name": "Infected Weeper", "type": "monster"},
  "490": {"name": "Orewalker", "type": "monster"},
  "491": {"name": "Lava Golem", "type": "monster"},
  "492": {"name": "Magma Crawler", "type": "monster"},
  "493": {"name": "Lost Gnome", "type": "monster"},
  "494": {"name": "Enslaved Dwarf", "type": "monster"},
  "495": {"name": "Abyssador", "type": "monster"},
  "496": {"name": "Lost Berserker", "type": "monster"},
  "497": {"name": "Cliff Strider", "type": "monster"},
  "498": {"name": "Ironblight", "type": "monster"},
  "499": {"name": "Hideous Fungus", "type": "monster"},
  "500": {"name": "Deathstrike", "type": "monster"},
  "501": {"name": "ID 501", "type": "monster"},
  "502": {"name": "ID 502", "type": "monster"},
  "503": {"name": "ID 503", "type": "monster"},
  "504": {"name": "Gnomevil", "type": "monster"},
  "505": {"name": "Dragonling", "type": "monster"},
  "506": {"name": "ID 506", "type": "monster"},
  "507": {"name": "ID 507", "type": "monster"},
  "508": {"name": "Damaged Crystal Golem", "type": "monster"},
  "509": {"name": "Vulcongra", "type": "monster"},
  "510": {"name": "Wiggler", "type": "monster"},
  "511": {"name": "Crystalcrusher", "type": "monster"},
  "512": {"name": "Crystal Warlord", "type": "male"},
  "513": {"name": "Crystal Warlord", "type": "female"},
  "514": {"name": "Soil Guardian", "type": "female"},
  "515": {"name": "Modified Gnarlhound", "type": "monster"},
  "516": {"name": "Soil Guardian", "type": "male"},
  "517": {"name": "Humorless Fungus", "type": "monster"},
  "518": {"name": "ID 518", "type": "monster"},
  "519": {"name": "ID 519", "type": "monster"},
  "520": {"name": "ID 520", "type": "monster"},
  "521": {"name": "ID 521", "type": "monster"},
  "522": {"name": "ID 522", "type": "monster"},
  "523": {"name": "Water Buffalo", "type": "monster"},
  "524": {"name": "ID 524", "type": "monster"},
  "525": {"name": "ID 525", "type": "monster"},
  "526": {"name": "ID 526", "type": "monster"},
  "527": {"name": "Drillworm", "type": "monster"},
  "528": {"name": "Dawnfly", "type": "monster"},
  "529": {"name": "Salamander", "type": "monster"},
  "530": {"name": "Marsh Stalker", "type": "monster"},
  "531": {"name": "Pigeon", "type": "monster"},
  "532": {"name": "Corym Charlatan", "type": "monster"},
  "533": {"name": "Corym Skirmisher", "type": "monster"},
  "534": {"name": "Cheese Thief", "type": "monster"},
  "535": {"name": "Woodling", "type": "monster"},
  "536": {"name": "ID 536", "type": "monster"},
  "537": {"name": "Lost Exile", "type": "monster"},
  "538": {"name": "Lost Basher", "type": "monster"},
  "539": {"name": "Lost Thrower", "type": "monster"},
  "540": {"name": "ID 540", "type": "monster"},
  "541": {"name": "Demon", "type": "male"},
  "542": {"name": "Demon", "type": "female"},
  "543": {"name": "ID 543", "type": "monster"},
  "544": {"name": "ID 544", "type": "monster"},
  "545": {"name": "ID 545", "type": "monster"},
  "546": {"name": "ID 546", "type": "monster"},
  "547": {"name": "ID 547", "type": "monster"},
  "548": {"name": "ID 548", "type": "monster"},
  "549": {"name": "ID 549", "type": "monster"},
  "550": {"name": "Rorc", "type": "monster"},
  "551": {"name": "Shadow Pupil", "type": "monster"},
  "552": {"name": "Blood Hand", "type": "monster"},
  "553": {"name": "Blood Priest", "type": "monster"},
  "554": {"name": "Mutated Visco", "type": "monster"},
  "555": {"name": "Vampire Viscount", "type": "monster"},
  "556": {"name": "Nightfiend", "type": "monster"},
  "557": {"name": "The Pale Count", "type": "monster"},
  "558": {"name": "Gravedigger", "type": "monster"},
  "559": {"name": "ID 559", "type": "monster"},
  "560": {"name": "Time Keeper", "type": "monster"},
  "561": {"name": "Elder Wyrm", "type": "monster"},
  "562": {"name": "Tyrn", "type": "monster"},
  "563": {"name": "The Welter", "type": "monster"},
  "564": {"name": "White Pale", "type": "monster"},
  "565": {"name": "Weakened Shlorg", "type": "monster"},
  "566": {"name": "Strong Soul", "type": "monster"},
  "567": {"name": "Leaf Golem", "type": "monster"},
  "568": {"name": "Enraged Soul", "type": "monster"},
  "569": {"name": "Forest Fury", "type": "monster"},
  "570": {"name": "Noble Lion", "type": "monster"},
  "571": {"name": "ID 571", "type": "monster"},
  "572": {"name": "ID 572", "type": "monster"},
  "573": {"name": "Wilting Leaf Golem", "type": "monster"},
  "574": {"name": "Cave Explorer", "type": "male"},
  "575": {"name": "Cave Explorer", "type": "female"},
  "576": {"name": "ID 576", "type": "monster"},
  "577": {"name": "Dream Warden", "type": "male"},
  "578": {"name": "Dream Warden", "type": "female"},
  "579": {"name": "Shock Head", "type": "monster"},
  "580": {"name": "ID 580", "type": "monster"},
  "581": {"name": "ID 581", "type": "monster"},
  "582": {"name": "ID 582", "type": "monster"},
  "583": {"name": "Sight of Surrender", "type": "monster"},
  "584": {"name": "Guzzlemaw", "type": "monster"},
  "585": {"name": "Enfeebled Silencer", "type": "monster"},
  "586": {"name": "Choking Fear", "type": "monster"},
  "587": {"name": "Terrorsleep", "type": "monster"},
  "588": {"name": "Retching Horror", "type": "monster"},
  "589": {"name": "ID 589", "type": "monster"},
  "590": {"name": "Demon Outcast", "type": "monster"},
  "591": {"name": "Gaz", "type": "monster"},
  "592": {"name": "Shiversleep", "type": "monster"},
  "593": {"name": "Feversleep", "type": "monster"},
  "594": {"name": "Memory of a Frazzlemaw", "type": "monster"},
  "595": {"name": "Reflection of Mawhawk", "type": "monster"},
  "596": {"name": "ID 596", "type": "monster"},
  "597": {"name": "ID 597", "type": "monster"},
  "598": {"name": "Canopic Jar", "type": "monster"},
  "599": {"name": "Greater Canopic Jar", "type": "monster"},
  "600": {"name": "Glooth Golem", "type": "monster"},
  "601": {"name": "Metal Gargoyle", "type": "monster"},
  "602": {"name": "Blood Beast", "type": "monster"},
  "603": {"name": "Rustheap Golem", "type": "monster"},
  "604": {"name": "Lisa", "type": "monster"},
  "605": {"name": "Walker", "type": "monster"},
  "606": {"name": "ID 606", "type": "monster"},
  "607": {"name": "Bullwark", "type": "monster"},
  "608": {"name": "Minotaur Amazon", "type": "monster"},
  "609": {"name": "Execowtioner", "type": "monster"},
  "610": {"name": "Glooth Engineer", "type": "male"},
  "611": {"name": "General Murius", "type": "monster"},
  "612": {"name": "Minotaur Hunter", "type": "monster"},
  "613": {"name": "Worm Priestess", "type": "monster"},
  "614": {"name": "Glooth Blob", "type": "monster"},
  "615": {"name": "Aggressive Matter", "type": "monster"},
  "616": {"name": "ID 616", "type": "monster"},
  "617": {"name": "Organic Matter", "type": "monster"},
  "618": {"name": "Glooth Engineer", "type": "female"},
  "619": {"name": "Jersey", "type": "male"},
  "620": {"name": "Jersey", "type": "female"},
  "621": {"name": "ID 621", "type": "monster"},
  "622": {"name": "ID 622", "type": "monster"},
  "623": {"name": "ID 623", "type": "monster"},
  "624": {"name": "ID 624", "type": "monster"},
  "625": {"name": "ID 625", "type": "monster"},
  "626": {"name": "Thorn Steed", "type": "monster"},
  "627": {"name": "ID 627", "type": "monster"},
  "628": {"name": "ID 628", "type": "monster"},
  "629": {"name": "ID 629", "type": "monster"},
  "630": {"name": "ID 630", "type": "monster"},
  "631": {"name": "ID 631", "type": "monster"},
  "632": {"name": "Champion", "type": "female"},
  "633": {"name": "Champion", "type": "male"},
  "634": {"name": "Conjurer", "type": "male"},
  "635": {"name": "Conjurer", "type": "female"},
  "636": {"name": "Beastmaster", "type": "female"},
  "637": {"name": "Beastmaster", "type": "male"},
  "638": {"name": "ID 638", "type": "monster"},
  "639": {"name": "ID 639", "type": "monster"},
  "640": {"name": "ID 640", "type": "monster"},
  "641": {"name": "ID 641", "type": "monster"},
  "642": {"name": "ID 642", "type": "monster"},
  "643": {"name": "ID 643", "type": "monster"},
  "644": {"name": "ID 644", "type": "monster"},
  "645": {"name": "ID 645", "type": "monster"},
  "646": {"name": "ID 646", "type": "monster"},
  "647": {"name": "ID 647", "type": "monster"},
  "648": {"name": "ID 648", "type": "monster"},
  "649": {"name": "ID 649", "type": "monster"},
  "650": {"name": "ID 650", "type": "monster"},
  "651": {"name": "ID 651", "type": "monster"},
  "652": {"name": "ID 652", "type": "monster"},
  "653": {"name": "ID 653", "type": "monster"},
  "654": {"name": "ID 654", "type": "monster"},
  "655": {"name": "ID 655", "type": "monster"},
  "656": {"name": "ID 656", "type": "monster"},
  "657": {"name": "ID 657", "type": "monster"},
  "658": {"name": "ID 658", "type": "monster"},
  "659": {"name": "ID 659", "type": "monster"},
  "660": {"name": "ID 660", "type": "monster"},
  "661": {"name": "ID 661", "type": "monster"},
  "662": {"name": "ID 662", "type": "monster"},
  "663": {"name": "ID 663", "type": "monster"},
  "664": {"name": "Chaos Acolyte", "type": "female"},
  "665": {"name": "Chaos Acolyte", "type": "male"},
  "666": {"name": "Death Herald", "type": "female"},
  "667": {"name": "Death Herald", "type": "male"},
  "668": {"name": "ID 668", "type": "monster"},
  "669": {"name": "ID 669", "type": "monster"},
  "670": {"name": "ID 670", "type": "monster"},
  "671": {"name": "ID 671", "type": "monster"},
  "672": {"name": "ID 672", "type": "monster"},
  "673": {"name": "ID 673", "type": "monster"},
  "674": {"name": "ID 674", "type": "monster"},
  "675": {"name": "Seacrest Serpent", "type": "monster"},
  "676": {"name": "Morbol", "type": "monster"},
  "677": {"name": "Empowered Glooth Horror", "type": "monster"},
  "678": {"name": "ID 678", "type": "monster"},
  "679": {"name": "Professor Maxxen", "type": "monster"},
  "680": {"name": "Glooth Bomb", "type": "monster"},
  "681": {"name": "Shadow Tentacle", "type": "monster"},
  "682": {"name": "ID 682", "type": "monster"},
  "683": {"name": "Ranger", "type": "female"},
  "684": {"name": "Ranger", "type": "male"},
  "685": {"name": "ID 685", "type": "monster"},
  "686": {"name": "ID 686", "type": "monster"},
  "687": {"name": "ID 687", "type": "monster"},
  "688": {"name": "ID 688", "type": "monster"},
  "689": {"name": "ID 689", "type": "monster"},
  "690": {"name": "ID 690", "type": "monster"},
  "691": {"name": "ID 691", "type": "monster"},
  "692": {"name": "ID 692", "type": "monster"},
  "693": {"name": "ID 693", "type": "monster"},
  "694": {"name": "Ceremonial Garb", "type": "female"},
  "695": {"name": "Ceremonial Garb", "type": "male"},
  "696": {"name": "Puppeteer", "type": "female"},
  "697": {"name": "Puppeteer", "type": "male"},
  "698": {"name": "Spirit Caller", "type": "female"},
  "699": {"name": "Spirit Caller", "type": "male"},
  "700": {"name": "ID 700", "type": "monster"},
  "701": {"name": "ID 701", "type": "monster"},
  "702": {"name": "ID 702", "type": "monster"},
  "703": {"name": "ID 703", "type": "monster"},
  "704": {"name": "ID 704", "type": "monster"},
  "705": {"name": "ID 705", "type": "monster"},
  "706": {"name": "ID 706", "type": "monster"},
  "707": {"name": "ID 707", "type": "monster"},
  "708": {"name": "ID 708", "type": "monster"},
  "709": {"name": "ID 709", "type": "monster"},
  "710": {"name": "ID 710", "type": "monster"},
  "711": {"name": "ID 711", "type": "monster"},
  "712": {"name": "Tainted Soul", "type": "monster"},
  "713": {"name": "ID 713", "type": "monster"},
  "714": {"name": "Dark Soul", "type": "monster"},
  "715": {"name": "ID 715", "type": "monster"},
  "716": {"name": "Gloom Wolf", "type": "monster"},
  "717": {"name": "Omnivora", "type": "monster"},
  "718": {"name": "ID 718", "type": "monster"},
  "719": {"name": "ID 719", "type": "monster"},
  "720": {"name": "Werebear", "type": "monster"},
  "721": {"name": "Wereboar", "type": "monster"},
  "722": {"name": "ID 722", "type": "monster"},
  "723": {"name": "ID 723", "type": "monster"},
  "724": {"name": "Evoker", "type": "female"},
  "725": {"name": "Evoker", "type": "male"},
  "726": {"name": "ID 726", "type": "monster"},
  "727": {"name": "ID 727", "type": "monster"},
  "728": {"name": "ID 728", "type": "monster"},
  "729": {"name": "Werebadger", "type": "monster"},
  "730": {"name": "Ghost Wolf", "type": "monster"},
  "731": {"name": "Feroxa2", "type": "monster"},
  "732": {"name": "Seaweaver", "type": "female"},
  "733": {"name": "Seaweaver", "type": "male"},
  "734": {"name": "ID 734", "type": "monster"},
  "735": {"name": "ID 735", "type": "monster"},
  "736": {"name": "ID 736", "type": "monster"},
  "737": {"name": "ID 737", "type": "monster"},
  "738": {"name": "ID 738", "type": "monster"},
  "739": {"name": "ID 739", "type": "monster"},
  "740": {"name": "ID 740", "type": "monster"},
  "741": {"name": "ID 741", "type": "monster"},
  "742": {"name": "ID 742", "type": "monster"},
  "743": {"name": "ID 743", "type": "monster"},
  "744": {"name": "ID 744", "type": "monster"},
  "745": {"name": "Recruiter", "type": "female"},
  "746": {"name": "Recruiter", "type": "male"},
  "747": {"name": "ID 747", "type": "monster"},
  "748": {"name": "ID 748", "type": "monster"},
  "749": {"name": "Sea Dog", "type": "female"},
  "750": {"name": "Sea Dog", "type": "male"},
  "751": {"name": "ID 751", "type": "monster"},
  "752": {"name": "ID 752", "type": "monster"},
  "753": {"name": "ID 753", "type": "monster"},
  "754": {"name": "ID 754", "type": "monster"},
  "755": {"name": "ID 755", "type": "monster"},
  "756": {"name": "ID 756", "type": "monster"},
  "757": {"name": "ID 757", "type": "monster"},
  "758": {"name": "ID 758", "type": "monster"},
  "759": {"name": "Royal Pumpkin", "type": "female"},
  "760": {"name": "Royal Pumpkin", "type": "male"},
  "761": {"name": "ID 761", "type": "monster"},
  "762": {"name": "ID 762", "type": "monster"},
  "763": {"name": "ID 763", "type": "monster"},
  "764": {"name": "ID 764", "type": "monster"},
  "765": {"name": "ID 765", "type": "monster"},
  "766": {"name": "ID 766", "type": "monster"},
  "767": {"name": "ID 767", "type": "monster"},
  "768": {"name": "ID 768", "type": "monster"},
  "769": {"name": "ID 769", "type": "monster"},
  "770": {"name": "ID 770", "type": "monster"},
  "771": {"name": "ID 771", "type": "monster"},
  "772": {"name": "ID 772", "type": "monster"},
  "773": {"name": "ID 773", "type": "monster"},
  "774": {"name": "ID 774", "type": "monster"},
  "775": {"name": "ID 775", "type": "monster"},
  "776": {"name": "ID 776", "type": "monster"},
  "777": {"name": "ID 777", "type": "monster"},
  "778": {"name": "ID 778", "type": "monster"},
  "779": {"name": "ID 779", "type": "monster"},
  "780": {"name": "ID 780", "type": "monster"},
  "781": {"name": "ID 781", "type": "monster"},
  "782": {"name": "ID 782", "type": "monster"},
  "783": {"name": "ID 783", "type": "monster"},
  "784": {"name": "ID 784", "type": "monster"},
  "785": {"name": "ID 785", "type": "monster"},
  "786": {"name": "ID 786", "type": "monster"},
  "787": {"name": "ID 787", "type": "monster"},
  "788": {"name": "ID 788", "type": "monster"},
  "789": {"name": "ID 789", "type": "monster"},
  "790": {"name": "ID 790", "type": "monster"},
  "791": {"name": "ID 791", "type": "monster"},
  "792": {"name": "ID 792", "type": "monster"},
  "793": {"name": "ID 793", "type": "monster"},
  "794": {"name": "ID 794", "type": "monster"},
  "795": {"name": "ID 795", "type": "monster"},
  "796": {"name": "ID 796", "type": "monster"},
  "797": {"name": "ID 797", "type": "monster"},
  "798": {"name": "ID 798", "type": "monster"},
  "799": {"name": "ID 799", "type": "monster"},
  "800": {"name": "ID 800", "type": "monster"},
  "801": {"name": "ID 801", "type": "monster"},
  "802": {"name": "ID 802", "type": "monster"},
  "803": {"name": "ID 803", "type": "monster"},
  "804": {"name": "ID 804", "type": "monster"},
  "805": {"name": "ID 805", "type": "monster"},
  "806": {"name": "ID 806", "type": "monster"},
  "807": {"name": "ID 807", "type": "monster"},
  "808": {"name": "ID 808", "type": "monster"},
  "809": {"name": "ID 809", "type": "monster"},
  "810": {"name": "ID 810", "type": "monster"},
  "811": {"name": "ID 811", "type": "monster"},
  "812": {"name": "ID 812", "type": "monster"},
  "813": {"name": "ID 813", "type": "monster"},
  "814": {"name": "ID 814", "type": "monster"},
  "815": {"name": "ID 815", "type": "monster"},
  "816": {"name": "ID 816", "type": "monster"},
  "817": {"name": "ID 817", "type": "monster"},
  "818": {"name": "ID 818", "type": "monster"},
  "819": {"name": "ID 819", "type": "monster"},
  "820": {"name": "ID 820", "type": "monster"},
  "821": {"name": "ID 821", "type": "monster"},
  "822": {"name": "ID 822", "type": "monster"},
  "823": {"name": "ID 823", "type": "monster"},
  "824": {"name": "ID 824", "type": "monster"},
  "825": {"name": "ID 825", "type": "monster"},
  "826": {"name": "ID 826", "type": "monster"},
  "827": {"name": "ID 827", "type": "monster"},
  "828": {"name": "ID 828", "type": "monster"},
  "829": {"name": "ID 829", "type": "monster"},
  "830": {"name": "ID 830", "type": "monster"},
  "831": {"name": "ID 831", "type": "monster"},
  "832": {"name": "ID 832", "type": "monster"},
  "833": {"name": "ID 833", "type": "monster"},
  "834": {"name": "ID 834", "type": "monster"},
  "835": {"name": "ID 835", "type": "monster"},
  "836": {"name": "ID 836", "type": "monster"},
  "837": {"name": "ID 837", "type": "monster"},
  "838": {"name": "ID 838", "type": "monster"},
  "839": {"name": "ID 839", "type": "monster"},
  "840": {"name": "ID 840", "type": "monster"},
  "841": {"name": "ID 841", "type": "monster"},
  "842": {"name": "Kroazur", "type": "monster"},
  "843": {"name": "Ferumbras Soul Splinter", "type": "monster"},
  "844": {"name": "Ascending Ferumbras", "type": "monster"},
  "845": {"name": "Rift Warrior", "type": "female"},
  "846": {"name": "Rift Warrior", "type": "male"},
  "847": {"name": "ID 847", "type": "monster"},
  "848": {"name": "ID 848", "type": "monster"},
  "849": {"name": "ID 849", "type": "monster"},
  "850": {"name": "ID 850", "type": "monster"},
  "851": {"name": "ID 851", "type": "monster"},
  "852": {"name": "Winter Warden", "type": "female"},
  "853": {"name": "Winter Warden", "type": "male"},
  "854": {"name": "Vexclaw", "type": "monster"},
  "855": {"name": "Grimeleech", "type": "monster"},
  "856": {"name": "Hellflayer", "type": "monster"},
  "857": {"name": "Memory of an Ogre", "type": "monster"},
  "858": {"name": "Ogre Savage", "type": "monster"},
  "859": {"name": "Ogre Shaman", "type": "monster"},
  "860": {"name": "Clomp", "type": "monster"},
  "861": {"name": "ID 861", "type": "monster"},
  "862": {"name": "Plagirath", "type": "monster"},
  "863": {"name": "Bone Capsule", "type": "monster"},
  "864": {"name": "ID 864", "type": "monster"},
  "865": {"name": "ID 865", "type": "monster"},
  "866": {"name": "ID 866", "type": "monster"},
  "867": {"name": "ID 867", "type": "monster"},
  "868": {"name": "ID 868", "type": "monster"},
  "869": {"name": "ID 869", "type": "monster"},
  "870": {"name": "ID 870", "type": "monster"},
  "871": {"name": "ID 871", "type": "monster"},
  "872": {"name": "ID 872", "type": "monster"},
  "873": {"name": "Philosopher", "type": "male"},
  "874": {"name": "Philosopher", "type": "female"},
  "875": {"name": "The Corruptor of Souls", "type": "monster"},
  "876": {"name": "Anomaly", "type": "monster"},
  "877": {"name": "Instable Sparkion", "type": "monster"},
  "878": {"name": "Breach Brood", "type": "monster"},
  "879": {"name": "Reality Reaver", "type": "monster"},
  "880": {"name": "ID 880", "type": "monster"},
  "881": {"name": "ID 881", "type": "monster"},
  "882": {"name": "Dread Intruder", "type": "monster"},
  "883": {"name": "ID 883", "type": "monster"},
  "884": {"name": "Arena Champion", "type": "male"},
  "885": {"name": "Arena Champion", "type": "female"},
  "886": {"name": "ID 886", "type": "monster"},
  "887": {"name": "ID 887", "type": "monster"},
  "888": {"name": "ID 888", "type": "monster"},
  "889": {"name": "ID 889", "type": "monster"},
  "890": {"name": "ID 890", "type": "monster"},
  "891": {"name": "ID 891", "type": "monster"},
  "892": {"name": "ID 892", "type": "monster"},
  "893": {"name": "ID 893", "type": "monster"},
  "894": {"name": "ID 894", "type": "monster"},
  "895": {"name": "ID 895", "type": "monster"},
  "896": {"name": "ID 896", "type": "monster"},
  "897": {"name": "ID 897", "type": "monster"},
  "898": {"name": "ID 898", "type": "monster"},
  "899": {"name": "Lupine Warden", "type": "male"},
  "900": {"name": "Lupine Warden", "type": "female"},
  "901": {"name": "ID 901", "type": "monster"},
  "902": {"name": "ID 902", "type": "monster"},
  "903": {"name": "ID 903", "type": "monster"},
  "904": {"name": "Icicle", "type": "monster"},
  "905": {"name": "ID 905", "type": "monster"},
  "906": {"name": "ID 906", "type": "monster"},
  "907": {"name": "ID 907", "type": "monster"},
  "908": {"name": "Grove Keeper", "type": "male"},
  "909": {"name": "Grove Keeper", "type": "female"},
  "910": {"name": "Old Giant Spider", "type": "monster"},
  "911": {"name": "ID 911", "type": "monster"},
  "912": {"name": "ID 912", "type": "monster"},
  "913": {"name": "ID 913", "type": "monster"},
  "914": {"name": "ID 914", "type": "monster"},
  "915": {"name": "ID 915", "type": "monster"},
  "916": {"name": "ID 916", "type": "monster"},
  "917": {"name": "ID 917", "type": "monster"},
  "918": {"name": "Memory of a Wolf", "type": "monster"},
  "919": {"name": "Old Bear", "type": "monster"},
  "920": {"name": "Old Bug", "type": "monster"},
  "921": {"name": "Old Pig", "type": "monster"},
  "922": {"name": "Old Spider", "type": "monster"},
  "923": {"name": "Old Wasp", "type": "monster"},
  "924": {"name": "Old Beholder", "type": "monster"},
  "925": {"name": "An Observer Eye", "type": "monster"},
  "926": {"name": "ID 926", "type": "monster"},
  "927": {"name": "ID 927", "type": "monster"},
  "928": {"name": "Zorvorax", "type": "monster"},
  "929": {"name": "Festive", "type": "female"},
  "930": {"name": "ID 930", "type": "monster"},
  "931": {"name": "Festive", "type": "male"},
  "932": {"name": "Memory of a Shaper", "type": "monster"},
  "933": {"name": "Shaper Matriarch", "type": "monster"},
  "934": {"name": "Orclops Doomhauler", "type": "monster"},
  "935": {"name": "Orclops Ravager", "type": "monster"},
  "936": {"name": "Stone Rhino", "type": "monster"},
  "937": {"name": "ID 937", "type": "monster"},
  "938": {"name": "Dragonking Zyrtarch", "type": "monster"},
  "939": {"name": "The Last Lore Keeper", "type": "monster"},
  "940": {"name": "Lloyd", "type": "monster"},
  "941": {"name": "ID 941", "type": "monster"},
  "942": {"name": "ID 942", "type": "monster"},
  "943": {"name": "The Freezing Time Guardian", "type": "monster"},
  "944": {"name": "The Blazing Time Guardian", "type": "monster"},
  "945": {"name": "The Time Guardian", "type": "monster"},
  "946": {"name": "ID 946", "type": "monster"},
  "947": {"name": "The First Dragon", "type": "monster"},
  "948": {"name": "ID 948", "type": "monster"},
  "949": {"name": "ID 949", "type": "monster"},
  "950": {"name": "ID 950", "type": "monster"},
  "951": {"name": "ID 951", "type": "monster"},
  "952": {"name": "ID 952", "type": "monster"},
  "953": {"name": "ID 953", "type": "monster"},
  "954": {"name": "ID 954", "type": "monster"},
  "955": {"name": "Pharaoh", "type": "male"},
  "956": {"name": "Pharaoh", "type": "female"},
  "957": {"name": "Trophy Hunter", "type": "male"},
  "958": {"name": "Trophy Hunter", "type": "female"},
  "959": {"name": "ID 959", "type": "monster"},
  "960": {"name": "ID 960", "type": "monster"},
  "961": {"name": "ID 961", "type": "monster"},
  "962": {"name": "Retro Warrior", "type": "male"},
  "963": {"name": "Retro Warrior", "type": "female"},
  "964": {"name": "Retro Summoner", "type": "male"},
  "965": {"name": "Retro Summoner", "type": "female"},
  "966": {"name": "Retro Nobleman", "type": "male"},
  "967": {"name": "Retro Noblewoman", "type": "female"},
  "968": {"name": "Retro Mage", "type": "male"},
  "969": {"name": "Retro Mage", "type": "female"},
  "970": {"name": "Retro Knight", "type": "male"},
  "971": {"name": "Retro Knight", "type": "female"},
  "972": {"name": "Retro Hunter", "type": "male"},
  "973": {"name": "Retro Hunter", "type": "female"},
  "974": {"name": "Retro Citizen", "type": "male"},
  "975": {"name": "Retro Citizen", "type": "female"},
  "976": {"name": "Putrid Mummy", "type": "monster"},
  "977": {"name": "Pooka", "type": "monster"},
  "978": {"name": "Twisted Pooka", "type": "monster"},
  "979": {"name": "Sphere of Wrath", "type": "monster"},
  "980": {"name": "Raxias", "type": "monster"},
  "981": {"name": "Boogy", "type": "monster"},
  "982": {"name": "Pixie", "type": "monster"},
  "983": {"name": "ID 983", "type": "monster"},
  "984": {"name": "The False God", "type": "monster"},
  "985": {"name": "Misguided Shadow", "type": "monster"},
  "986": {"name": "Liquor Spirit", "type": "monster"},
  "987": {"name": "The Armored Voidborn", "type": "monster"},
  "988": {"name": "Leiden", "type": "monster"},
  "989": {"name": "Nymph", "type": "monster"},
  "990": {"name": "Barkless Devotee", "type": "monster"},
  "991": {"name": "Knight familiar", "type": "monster"},
  "992": {"name": "Paladin familiar", "type": "monster"},
  "993": {"name": "Druid familiar", "type": "monster"},
  "994": {"name": "Sorcerer familiar", "type": "monster"},
  "995": {"name": "ID 995", "type": "monster"},
  "996": {"name": "ID 996", "type": "monster"},
  "997": {"name": "ID 997", "type": "monster"},
  "998": {"name": "ID 998", "type": "monster"},
  "999": {"name": "ID 999", "type": "monster"},
  "1000": {"name": "ID 1000", "type": "monster"},
  "1001": {"name": "ID 1001", "type": "monster"},
  "1002": {"name": "ID 1002", "type": "monster"},
  "1003": {"name": "ID 1003", "type": "monster"},
  "1004": {"name": "ID 1004", "type": "monster"},
  "1005": {"name": "ID 1005", "type": "monster"},
  "1006": {"name": "ID 1006", "type": "monster"},
  "1007": {"name": "ID 1007", "type": "monster"},
  "1008": {"name": "ID 1008", "type": "monster"},
  "1009": {"name": "ID 1009", "type": "monster"},
  "1010": {"name": "ID 1010", "type": "monster"},
  "1011": {"name": "Minotaur Idol", "type": "monster"},
  "1012": {"name": "ID 1012", "type": "monster"},
  "1013": {"name": "The Sandking", "type": "monster"},
  "1014": {"name": "ID 1014", "type": "monster"},
  "1015": {"name": "ID 1015", "type": "monster"},
  "1016": {"name": "ID 1016", "type": "monster"},
  "1017": {"name": "ID 1017", "type": "monster"},
  "1018": {"name": "ID 1018", "type": "monster"},
  "1019": {"name": "ID 1019", "type": "monster"},
  "1020": {"name": "Herbalist", "type": "female"},
  "1021": {"name": "Herbalist", "type": "male"},
  "1022": {"name": "ID 1022", "type": "monster"},
  "1023": {"name": "Sun Priest", "type": "male"},
  "1024": {"name": "Sun Priest", "type": "female"},
  "1025": {"name": "ID 1025", "type": "monster"},
  "1026": {"name": "ID 1026", "type": "monster"},
  "1027": {"name": "ID 1027", "type": "monster"},
  "1028": {"name": "ID 1028", "type": "monster"},
  "1029": {"name": "Fox", "type": "monster"},
  "1030": {"name": "Werefox", "type": "monster"},
  "1031": {"name": "Sharpclaw", "type": "monster"},
  "1032": {"name": "Stonerefiner", "type": "monster"},
  "1033": {"name": "Deepworm", "type": "monster"},
  "1034": {"name": "Diremaw", "type": "monster"},
  "1035": {"name": "Tunnel Tyrant", "type": "monster"},
  "1036": {"name": "Cave Devourer", "type": "monster"},
  "1037": {"name": "Chasm Spawn", "type": "monster"},
  "1038": {"name": "Black Vixen", "type": "monster"},
  "1039": {"name": "Bloodback", "type": "monster"},
  "1040": {"name": "Shadowpelt", "type": "monster"},
  "1041": {"name": "Lava Lurker", "type": "monster"},
  "1042": {"name": "Makeshift Warrior", "type": "male"},
  "1043": {"name": "Makeshift Warrior", "type": "female"},
  "1044": {"name": "Last Planegazer", "type": "monster"},
  "1045": {"name": "The Baron from Below", "type": "monster"},
  "1046": {"name": "The Count of the Core", "type": "monster"},
  "1047": {"name": "The Duke of the Depths", "type": "monster"},
  "1048": {"name": "Mole", "type": "monster"},
  "1049": {"name": "ID 1049", "type": "monster"},
  "1050": {"name": "Siege Master", "type": "female"},
  "1051": {"name": "Siege Master", "type": "male"},
  "1052": {"name": "ID 1052", "type": "monster"},
  "1053": {"name": "ID 1053", "type": "monster"},
  "1054": {"name": "ID 1054", "type": "monster"},
  "1055": {"name": "Ancient Spawn of Morgathla", "type": "monster"},
  "1056": {"name": "Mercenary", "type": "male"},
  "1057": {"name": "Mercenary", "type": "female"},
  "1058": {"name": "Animated Feather", "type": "monster"},
  "1059": {"name": "Brain Squid", "type": "monster"},
  "1060": {"name": "Memory of a Book", "type": "monster"},
  "1061": {"name": "The Book of Death", "type": "monster"},
  "1062": {"name": "Ghulosh", "type": "monster"},
  "1063": {"name": "Floating Savant", "type": "monster"},
  "1064": {"name": "Ink Splash", "type": "monster"},
  "1065": {"name": "Knowledge Elemental", "type": "monster"},
  "1066": {"name": "Biting Book", "type": "monster"},
  "1067": {"name": "Librarian", "type": "monster"},
  "1068": {"name": "True Dawnfire Asura", "type": "monster"},
  "1069": {"name": "Battle Mage", "type": "male"},
  "1070": {"name": "Battle Mage", "type": "female"},
  "1071": {"name": "Ancient Lion Knight", "type": "monster"},
  "1072": {"name": "Grand Master Oberon", "type": "monster"},
  "1073": {"name": "Deathling Scout", "type": "monster"},
  "1074": {"name": "ID 1074", "type": "monster"},
  "1075": {"name": "ID 1075", "type": "monster"},
  "1076": {"name": "Brokul", "type": "monster"},
  "1077": {"name": "Thawing Dragon Lord", "type": "monster"},
  "1078": {"name": "Preceptor Lazare", "type": "monster"},
  "1079": {"name": "ID 1079", "type": "monster"},
  "1080": {"name": "ID 1080", "type": "monster"},
  "1081": {"name": "ID 1081", "type": "monster"},
  "1082": {"name": "ID 1082", "type": "monster"},
  "1083": {"name": "ID 1083", "type": "monster"},
  "1084": {"name": "ID 1084", "type": "monster"},
  "1085": {"name": "ID 1085", "type": "monster"},
  "1086": {"name": "ID 1086", "type": "monster"},
  "1087": {"name": "ID 1087", "type": "monster"},
  "1088": {"name": "Deathling Spellsinger", "type": "monster"},
  "1089": {"name": "ID 1089", "type": "monster"},
  "1090": {"name": "ID 1090", "type": "monster"},
  "1091": {"name": "ID 1091", "type": "monster"},
  "1092": {"name": "ID 1092", "type": "monster"},
  "1093": {"name": "ID 1093", "type": "monster"},
  "1094": {"name": "Discoverer", "type": "male"},
  "1095": {"name": "Discoverer", "type": "female"},
  "1096": {"name": "ID 1096", "type": "monster"},
  "1097": {"name": "ID 1097", "type": "monster"},
  "1098": {"name": "ID 1098", "type": "monster"},
  "1099": {"name": "ID 1099", "type": "monster"},
  "1100": {"name": "ID 1100", "type": "monster"},
  "1101": {"name": "ID 1101", "type": "monster"},
  "1102": {"name": "Sinister Archer", "type": "male"},
  "1103": {"name": "Sinister Archer", "type": "female"},
  "1104": {"name": "ID 1104", "type": "monster"},
  "1105": {"name": "ID 1105", "type": "monster"},
  "1106": {"name": "ID 1106", "type": "monster"},
  "1107": {"name": "ID 1107", "type": "monster"},
  "1108": {"name": "ID 1108", "type": "monster"},
  "1109": {"name": "ID 1109", "type": "monster"},
  "1110": {"name": "ID 1110", "type": "monster"},
  "1111": {"name": "ID 1111", "type": "monster"},
  "1112": {"name": "ID 1112", "type": "monster"},
  "1113": {"name": "ID 1113", "type": "monster"},
  "1114": {"name": "ID 1114", "type": "monster"},
  "1115": {"name": "ID 1115", "type": "monster"},
  "1116": {"name": "ID 1116", "type": "monster"},
  "1117": {"name": "ID 1117", "type": "monster"},
  "1118": {"name": "ID 1118", "type": "monster"},
  "1119": {"name": "Faceless Bane", "type": "monster"},
  "1120": {"name": "Malofur Mangrinder", "type": "monster"},
  "1121": {"name": "Plagueroot", "type": "monster"},
  "1122": {"name": "Burster Spectre", "type": "monster"},
  "1123": {"name": "ID 1123", "type": "monster"},
  "1124": {"name": "ID 1124", "type": "monster"},
  "1125": {"name": "ID 1125", "type": "monster"},
  "1126": {"name": "ID 1126", "type": "monster"},
  "1127": {"name": "Pumpkin Mummy", "type": "male"},
  "1128": {"name": "Pumpkin Mummy", "type": "female"},
  "1129": {"name": "ID 1129", "type": "monster"},
  "1130": {"name": "ID 1130", "type": "monster"},
  "1131": {"name": "ID 1131", "type": "monster"},
  "1132": {"name": "ID 1132", "type": "monster"},
  "1133": {"name": "Lumbering Carnivor", "type": "monster"},
  "1134": {"name": "Thanatursus", "type": "monster"},
  "1135": {"name": "Arachnophobica", "type": "monster"},
  "1136": {"name": "Crazed Summer Rearguard", "type": "monster"},
  "1137": {"name": "Crazed Summer Vanguard", "type": "monster"},
  "1138": {"name": "Menacing Carnivor", "type": "monster"},
  "1139": {"name": "Spiky Carnivor", "type": "monster"},
  "1140": {"name": "ID 1140", "type": "monster"},
  "1141": {"name": "ID 1141", "type": "monster"},
  "1142": {"name": "Maxxenius", "type": "monster"},
  "1143": {"name": "Alptramun", "type": "monster"},
  "1144": {"name": "The Nightmare Beast", "type": "monster"},
  "1145": {"name": "ID 1145", "type": "monster"},
  "1146": {"name": "Dream Warrior", "type": "male"},
  "1147": {"name": "Dream Warrior", "type": "female"},
  "1148": {"name": "Lacewing Moth", "type": "monster"},
  "1149": {"name": "Hibernal Moth", "type": "monster"},
  "1150": {"name": "ID 1150", "type": "monster"},
  "1151": {"name": "ID 1151", "type": "monster"},
  "1152": {"name": "ID 1152", "type": "monster"},
  "1153": {"name": "ID 1153", "type": "monster"},
  "1154": {"name": "ID 1154", "type": "monster"},
  "1155": {"name": "ID 1155", "type": "monster"},
  "1156": {"name": "ID 1156", "type": "monster"},
  "1157": {"name": "Baleful Bunny", "type": "monster"},
  "1158": {"name": "Bonny Bunny", "type": "monster"},
  "1159": {"name": "Animated Snowman", "type": "monster"},
  "1160": {"name": "ID 1160", "type": "monster"},
  "1161": {"name": "Percht Raider", "type": "male"},
  "1162": {"name": "Percht Raider", "type": "female"},
  "1163": {"name": "Cold Percht Sleigh", "type": "monster"},
  "1164": {"name": "Bright Percht Sleigh", "type": "monster"},
  "1165": {"name": "Dark Percht Sleigh", "type": "monster"},
  "1166": {"name": "ID 1166", "type": "monster"},
  "1167": {"name": "ID 1167", "type": "monster"},
  "1168": {"name": "ID 1168", "type": "monster"},
  "1169": {"name": "ID 1169", "type": "monster"},
  "1170": {"name": "ID 1170", "type": "monster"},
  "1171": {"name": "ID 1171", "type": "monster"},
  "1172": {"name": "ID 1172", "type": "monster"},
  "1173": {"name": "Owl Keeper", "type": "male"},
  "1174": {"name": "Owl Keeper", "type": "female"},
  "1175": {"name": "Cart Packed with Gold", "type": "monster"},
  "1176": {"name": "ID 1176", "type": "monster"},
  "1177": {"name": "ID 1177", "type": "monster"},
  "1178": {"name": "ID 1178", "type": "monster"},
  "1179": {"name": "ID 1179", "type": "monster"},
  "1180": {"name": "ID 1180", "type": "monster"},
  "1181": {"name": "ID 1181", "type": "monster"},
  "1182": {"name": "ID 1182", "type": "monster"},
  "1183": {"name": "ID 1183", "type": "monster"},
  "1184": {"name": "ID 1184", "type": "monster"},
  "1185": {"name": "ID 1185", "type": "monster"},
  "1186": {"name": "Guidon Bearer", "type": "male"},
  "1187": {"name": "Guidon Bearer", "type": "female"},
  "1188": {"name": "Feral Sphinx", "type": "monster"},
  "1189": {"name": "Memory of a Manticore", "type": "monster"},
  "1190": {"name": "Crypt Warden", "type": "monster"},
  "1191": {"name": "ID 1191", "type": "monster"},
  "1192": {"name": "ID 1192", "type": "monster"},
  "1193": {"name": "ID 1193", "type": "monster"},
  "1194": {"name": "ID 1194", "type": "monster"},
  "1195": {"name": "Sun-Marked Goanna", "type": "monster"},
  "1196": {"name": "Yirkas Blue Scales", "type": "monster"},
  "1197": {"name": "Urmahlullu the Immaculate", "type": "monster"},
  "1198": {"name": "ID 1198", "type": "monster"},
  "1199": {"name": "Priestess of the Wild Sun", "type": "monster"},
  "1200": {"name": "Black Sphinx Acolyte", "type": "monster"},
  "1201": {"name": "Scarlett Etzel", "type": "monster"},
  "1202": {"name": "Void Master", "type": "male"},
  "1203": {"name": "Void Master", "type": "female"},
  "1204": {"name": "Veteran Paladin", "type": "male"},
  "1205": {"name": "Veteran Paladin", "type": "female"},
  "1206": {"name": "Lion of War", "type": "male"},
  "1207": {"name": "Lion of War", "type": "female"},
  "1208": {"name": "ID 1208", "type": "monster"},
  "1209": {"name": "ID 1209", "type": "monster"},
  "1210": {"name": "Golden", "type": "male"},
  "1211": {"name": "Golden", "type": "female"},
  "1212": {"name": "Ogre Ruffian", "type": "monster"},
  "1213": {"name": "Ogre Rowdy", "type": "monster"},
  "1214": {"name": "Ogre Sage", "type": "monster"},
  "1215": {"name": "ID 1215", "type": "monster"},
  "1216": {"name": "ID 1216", "type": "monster"},
  "1217": {"name": "Custodian", "type": "monster"},
  "1218": {"name": "Ugly Monster", "type": "monster"},
  "1219": {"name": "ID 1219", "type": "monster"},
  "1220": {"name": "Gryphon", "type": "monster"},
  "1221": {"name": "Count Vlarkorth", "type": "monster"},
  "1222": {"name": "Sir Baeloc", "type": "monster"},
  "1223": {"name": "Earl Osam", "type": "monster"},
  "1224": {"name": "King Zelos", "type": "monster"},
  "1225": {"name": "ID 1225", "type": "monster"},
  "1226": {"name": "ID 1226", "type": "monster"},
  "1227": {"name": "ID 1227", "type": "monster"},
  "1228": {"name": "ID 1228", "type": "monster"},
  "1229": {"name": "ID 1229", "type": "monster"},
  "1230": {"name": "ID 1230", "type": "monster"},
  "1231": {"name": "ID 1231", "type": "monster"},
  "1232": {"name": "ID 1232", "type": "monster"},
  "1233": {"name": "ID 1233", "type": "monster"},
  "1234": {"name": "ID 1234", "type": "monster"},
  "1235": {"name": "ID 1235", "type": "monster"},
  "1236": {"name": "ID 1236", "type": "monster"},
  "1237": {"name": "ID 1237", "type": "monster"},
  "1238": {"name": "ID 1238", "type": "monster"},
  "1239": {"name": "ID 1239", "type": "monster"},
  "1240": {"name": "ID 1240", "type": "monster"},
  "1241": {"name": "ID 1241", "type": "monster"},
  "1242": {"name": "ID 1242", "type": "monster"},
  "1243": {"name": "Hand of the Inquisition", "type": "male"},
  "1244": {"name": "Hand of the Inquisition", "type": "female"},
  "1245": {"name": "Breezy Garb", "type": "male"},
  "1246": {"name": "Breezy Garb", "type": "female"},
  "1247": {"name": "ID 1247", "type": "monster"},
  "1248": {"name": "ID 1248", "type": "monster"},
  "1249": {"name": "ID 1249", "type": "monster"},
  "1250": {"name": "ID 1250", "type": "monster"},
  "1251": {"name": "Orcsoberfest Garb", "type": "male"},
  "1252": {"name": "Orcsoberfest Garb", "type": "female"},
  "1253": {"name": "ID 1253", "type": "monster"},
  "1254": {"name": "ID 1254", "type": "monster"},
  "1255": {"name": "ID 1255", "type": "monster"},
  "1256": {"name": "ID 1256", "type": "monster"},
  "1257": {"name": "ID 1257", "type": "monster"},
  "1258": {"name": "ID 1258", "type": "monster"},
  "1259": {"name": "ID 1259", "type": "monster"},
  "1260": {"name": "ID 1260", "type": "monster"},
  "1261": {"name": "ID 1261", "type": "monster"},
  "1262": {"name": "ID 1262", "type": "monster"},
  "1263": {"name": "ID 1263", "type": "monster"},
  "1264": {"name": "ID 1264", "type": "monster"},
  "1265": {"name": "ID 1265", "type": "monster"},
  "1266": {"name": "ID 1266", "type": "monster"},
  "1267": {"name": "ID 1267", "type": "monster"},
  "1268": {"name": "Irgix The Flimsy", "type": "monster"},
  "1269": {"name": "ID 1269", "type": "monster"},
  "1270": {"name": "Poltergeist", "type": "male"},
  "1271": {"name": "Poltergeist", "type": "female"},
  "1272": {"name": "The Pale Worm", "type": "monster"},
  "1273": {"name": "ID 1273", "type": "monster"},
  "1274": {"name": "ID 1274", "type": "monster"},
  "1275": {"name": "Wormling", "type": "monster"},
  "1276": {"name": "The Fear Feaster", "type": "monster"},
  "1277": {"name": "The Unwelcome", "type": "monster"},
  "1278": {"name": "The Dread Maiden", "type": "monster"},
  "1279": {"name": "Herder", "type": "male"},
  "1280": {"name": "Herder", "type": "female"},
  "1281": {"name": "ID 1281", "type": "monster"},
  "1282": {"name": "Falconer", "type": "male"},
  "1283": {"name": "Falconer", "type": "female"},
  "1284": {"name": "ID 1284", "type": "monster"},
  "1285": {"name": "ID 1285", "type": "monster"},
  "1286": {"name": "ID 1286", "type": "monster"},
  "1287": {"name": "ID 1287", "type": "monster"},
  "1288": {"name": "Dragon Slayer", "type": "male"},
  "1289": {"name": "Dragon Slayer", "type": "female"},
  "1290": {"name": "White Lion", "type": "monster"},
  "1291": {"name": "ID 1291", "type": "monster"},
  "1292": {"name": "Trailblazer", "type": "male"},
  "1293": {"name": "Trailblazer", "type": "female"},
  "1294": {"name": "Mean Maw", "type": "monster"},
  "1295": {"name": "Cloak of Terror", "type": "monster"},
  "1296": {"name": "Poor Soul", "type": "monster"},
  "1297": {"name": "Branchy Crawler", "type": "monster"},
  "1298": {"name": "Hazardous Phantom", "type": "monster"},
  "1299": {"name": "Brachiodemon", "type": "monster"},
  "1300": {"name": "Werehyaena", "type": "monster"},
  "1301": {"name": "Memory of a Werelion", "type": "monster"},
  "1302": {"name": "ID 1302", "type": "monster"},
  "1303": {"name": "Goshnar", "type": "monster"},
  "1304": {"name": "Goshnar", "type": "monster"},
  "1305": {"name": "Goshnar", "type": "monster"},
  "1306": {"name": "Aspect of Power", "type": "monster"},
  "1307": {"name": "Goshnar", "type": "monster"},
  "1308": {"name": "Goshnar", "type": "monster"},
  "1309": {"name": "ID 1309", "type": "monster"},
  "1310": {"name": "ID 1310", "type": "monster"},
  "1311": {"name": "ID 1311", "type": "monster"},
  "1312": {"name": "Rotten Golem", "type": "monster"},
  "1313": {"name": "Infernal Demon", "type": "monster"},
  "1314": {"name": "Turbulent Elemental", "type": "monster"},
  "1315": {"name": "Courage Leech", "type": "monster"},
  "1316": {"name": "Hardened Usurper Archer", "type": "monster"},
  "1317": {"name": "Hardened Usurper Knight", "type": "monster"},
  "1318": {"name": "ID 1318", "type": "monster"},
  "1319": {"name": "ID 1319", "type": "monster"},
  "1320": {"name": "ID 1320", "type": "monster"},
  "1321": {"name": "ID 1321", "type": "monster"},
  "1322": {"name": "Revenant", "type": "male"},
  "1323": {"name": "Revenant", "type": "female"},
  "1324": {"name": "ID 1324", "type": "monster"},
  "1325": {"name": "ID 1325", "type": "monster"},
  "1326": {"name": "ID 1326", "type": "monster"},
  "1327": {"name": "ID 1327", "type": "monster"},
  "1328": {"name": "ID 1328", "type": "monster"},
  "1329": {"name": "ID 1329", "type": "monster"},
  "1330": {"name": "ID 1330", "type": "monster"},
  "1331": {"name": "Jouster", "type": "male"},
  "1332": {"name": "Jouster", "type": "female"},
  "1333": {"name": "ID 1333", "type": "monster"},
  "1334": {"name": "ID 1334", "type": "monster"},
  "1335": {"name": "ID 1335", "type": "monster"},
  "1336": {"name": "ID 1336", "type": "monster"},
  "1337": {"name": "Goshnar", "type": "monster"},
  "1338": {"name": "Moth Cape", "type": "male"},
  "1339": {"name": "Moth Cape", "type": "female"},
  "1340": {"name": "ID 1340", "type": "monster"},
  "1341": {"name": "ID 1341", "type": "monster"},
  "1342": {"name": "ID 1342", "type": "monster"},
  "1343": {"name": "ID 1343", "type": "monster"},
  "1344": {"name": "Exotic Cave Spider", "type": "monster"},
  "1345": {"name": "ID 1345", "type": "monster"},
  "1346": {"name": "Pirat Artillerist", "type": "monster"},
  "1347": {"name": "ID 1347", "type": "monster"},
  "1348": {"name": "ID 1348", "type": "monster"},
  "1349": {"name": "ID 1349", "type": "monster"},
  "1350": {"name": "ID 1350", "type": "monster"},
  "1351": {"name": "ID 1351", "type": "monster"},
  "1352": {"name": "ID 1352", "type": "monster"},
  "1353": {"name": "ID 1353", "type": "monster"},
  "1354": {"name": "ID 1354", "type": "monster"},
  "1355": {"name": "ID 1355", "type": "monster"},
  "1356": {"name": "ID 1356", "type": "monster"},
  "1357": {"name": "ID 1357", "type": "monster"},
  "1358": {"name": "ID 1358", "type": "monster"},
  "1359": {"name": "ID 1359", "type": "monster"},
  "1360": {"name": "ID 1360", "type": "monster"},
  "1361": {"name": "ID 1361", "type": "monster"},
  "1362": {"name": "ID 1362", "type": "monster"},
  "1363": {"name": "ID 1363", "type": "monster"},
  "1364": {"name": "ID 1364", "type": "monster"},
  "1365": {"name": "ID 1365", "type": "monster"},
  "1366": {"name": "ID 1366", "type": "monster"},
  "1367": {"name": "ID 1367", "type": "monster"},
  "1368": {"name": "ID 1368", "type": "monster"},
  "1369": {"name": "ID 1369", "type": "monster"},
  "1370": {"name": "ID 1370", "type": "monster"},
  "1371": {"name": "Rascoohan", "type": "male"},
  "1372": {"name": "Rascoohan", "type": "female"},
  "1373": {"name": "Exotic Bat", "type": "monster"},
  "1374": {"name": "ID 1374", "type": "monster"},
  "1375": {"name": "ID 1375", "type": "monster"},
  "1376": {"name": "ID 1376", "type": "monster"},
  "1377": {"name": "Ratmiral Blackwhiskers", "type": "monster"},
  "1378": {"name": "ID 1378", "type": "monster"},
  "1379": {"name": "ID 1379", "type": "monster"},
  "1380": {"name": "ID 1380", "type": "monster"},
  "1381": {"name": "ID 1381", "type": "monster"},
  "1382": {"name": "Merry Garb", "type": "male"},
  "1383": {"name": "Merry Garb", "type": "female"},
  "1384": {"name": "Rune Master", "type": "male"},
  "1385": {"name": "Rune Master", "type": "female"},
  "1386": {"name": "Citizen of Issavi", "type": "male"},
  "1387": {"name": "Citizen of Issavi", "type": "female"},
  "1388": {"name": "ID 1388", "type": "monster"},
  "1389": {"name": "ID 1389", "type": "monster"},
  "1390": {"name": "ID 1390", "type": "monster"},
  "1391": {"name": "ID 1391", "type": "monster"},
  "1392": {"name": "ID 1392", "type": "monster"},
  "1393": {"name": "The Abomination", "type": "monster"},
  "1394": {"name": "Lavaworm", "type": "monster"},
  "1395": {"name": "ID 1395", "type": "monster"},
  "1396": {"name": "Tremendous Tyrant", "type": "monster"},
  "1397": {"name": "Varnished Diremaw", "type": "monster"},
  "1398": {"name": "Streaked Devourer", "type": "monster"},
  "1399": {"name": "Eyeless Devourer", "type": "monster"},
  "1400": {"name": "ID 1400", "type": "monster"},
  "1401": {"name": "Blemished Spawn", "type": "monster"},
  "1402": {"name": "ID 1402", "type": "monster"},
  "1403": {"name": "Afflicted Strider", "type": "monster"},
  "1404": {"name": "ID 1404", "type": "monster"},
  "1405": {"name": "Lavafungus", "type": "monster"},
  "1406": {"name": "Cave Chimera", "type": "monster"},
  "1407": {"name": "Girtablilu Warrior", "type": "monster"},
  "1408": {"name": "Bashmu", "type": "monster"},
  "1409": {"name": "ID 1409", "type": "monster"},
  "1410": {"name": "ID 1410", "type": "monster"},
  "1411": {"name": "ID 1411", "type": "monster"},
  "1412": {"name": "The Brainstealer", "type": "monster"},
  "1413": {"name": "Magma Bubble", "type": "monster"},
  "1414": {"name": "Lava Creature", "type": "monster"},
  "1415": {"name": "Forest Warden", "type": "male"},
  "1416": {"name": "Forest Warden", "type": "female"},
  "1417": {"name": "ID 1417", "type": "monster"},
  "1418": {"name": "Memory of a Carnisylvan", "type": "monster"},
  "1419": {"name": "Carnisylvan Sapling", "type": "monster"},
  "1420": {"name": "ID 1420", "type": "monster"},
  "1421": {"name": "ID 1421", "type": "monster"},
  "1422": {"name": "ID 1422", "type": "monster"},
  "1423": {"name": "ID 1423", "type": "monster"},
  "1424": {"name": "ID 1424", "type": "monster"},
  "1425": {"name": "ID 1425", "type": "monster"},
  "1426": {"name": "ID 1426", "type": "monster"},
  "1427": {"name": "ID 1427", "type": "monster"},
  "1428": {"name": "ID 1428", "type": "monster"},
  "1429": {"name": "ID 1429", "type": "monster"},
  "1430": {"name": "ID 1430", "type": "monster"},
  "1431": {"name": "ID 1431", "type": "monster"},
  "1432": {"name": "ID 1432", "type": "monster"},
  "1433": {"name": "ID 1433", "type": "monster"},
  "1434": {"name": "ID 1434", "type": "monster"},
  "1435": {"name": "ID 1435", "type": "monster"},
  "1436": {"name": "Royal Bounacean Advisor", "type": "male"},
  "1437": {"name": "Royal Bounacean Advisor", "type": "female"},
  "1438": {"name": "ID 1438", "type": "monster"},
  "1439": {"name": "ID 1439", "type": "monster"},
  "1440": {"name": "ID 1440", "type": "monster"},
  "1441": {"name": "ID 1441", "type": "monster"},
  "1442": {"name": "ID 1442", "type": "monster"},
  "1443": {"name": "ID 1443", "type": "monster"},
  "1444": {"name": "Dragon Knight", "type": "male"},
  "1445": {"name": "Dragon Knight", "type": "female"},
  "1446": {"name": "ID 1446", "type": "monster"},
  "1447": {"name": "ID 1447", "type": "monster"},
  "1448": {"name": "ID 1448", "type": "monster"},
  "1449": {"name": "Arbalester", "type": "male"},
  "1450": {"name": "Arbalester", "type": "female"},
  "1451": {"name": "ID 1451", "type": "monster"},
  "1452": {"name": "ID 1452", "type": "monster"},
  "1453": {"name": "ID 1453", "type": "monster"},
  "1454": {"name": "ID 1454", "type": "monster"},
  "1455": {"name": "ID 1455", "type": "monster"},
  "1456": {"name": "Royal Costume", "type": "female"},
  "1457": {"name": "Royal Costume", "type": "male"},
  "1458": {"name": "ID 1458", "type": "monster"},
  "1459": {"name": "ID 1459", "type": "monster"},
  "1460": {"name": "Formal Dress", "type": "male"},
  "1461": {"name": "Formal Dress", "type": "female"},
  "1462": {"name": "ID 1462", "type": "monster"},
  "1463": {"name": "ID 1463", "type": "monster"},
  "1464": {"name": "ID 1464", "type": "monster"},
  "1465": {"name": "ID 1465", "type": "monster"},
  "1466": {"name": "ID 1466", "type": "monster"},
  "1467": {"name": "ID 1467", "type": "monster"},
  "1468": {"name": "Morshabaal", "type": "monster"},
  "1469": {"name": "ID 1469", "type": "monster"},
  "1470": {"name": "ID 1470", "type": "monster"},
  "1471": {"name": "ID 1471", "type": "monster"},
  "1472": {"name": "ID 1472", "type": "monster"},
  "1473": {"name": "ID 1473", "type": "monster"},
  "1474": {"name": "ID 1474", "type": "monster"},
  "1475": {"name": "ID 1475", "type": "monster"},
  "1476": {"name": "ID 1476", "type": "monster"},
  "1477": {"name": "ID 1477", "type": "monster"},
  "1478": {"name": "ID 1478", "type": "monster"},
  "1479": {"name": "ID 1479", "type": "monster"},
  "1480": {"name": "ID 1480", "type": "monster"},
  "1481": {"name": "ID 1481", "type": "monster"},
  "1482": {"name": "ID 1482", "type": "monster"},
  "1483": {"name": "ID 1483", "type": "monster"},
  "1484": {"name": "ID 1484", "type": "monster"},
  "1485": {"name": "ID 1485", "type": "monster"},
  "1486": {"name": "ID 1486", "type": "monster"},
  "1487": {"name": "ID 1487", "type": "monster"},
  "1488": {"name": "ID 1488", "type": "monster"},
  "1489": {"name": "Ghost Blade", "type": "male"},
  "1490": {"name": "Ghost Blade", "type": "female"},
  "1491": {"name": "ID 1491", "type": "monster"},
  "1492": {"name": "ID 1492", "type": "monster"},
  "1493": {"name": "ID 1493", "type": "monster"},
  "1494": {"name": "ID 1494", "type": "monster"},
  "1495": {"name": "ID 1495", "type": "monster"},
  "1496": {"name": "ID 1496", "type": "monster"},
  "1497": {"name": "ID 1497", "type": "monster"},
  "1498": {"name": "ID 1498", "type": "monster"},
  "1499": {"name": "ID 1499", "type": "monster"},
  "1500": {"name": "Nordic Chieftain", "type": "male"},
  "1501": {"name": "Nordic Chieftain", "type": "female"},
  "1502": {"name": "ID 1502", "type": "monster"},
  "1503": {"name": "ID 1503", "type": "monster"},
  "1504": {"name": "ID 1504", "type": "monster"},
  "1505": {"name": "ID 1505", "type": "monster"},
  "1506": {"name": "ID 1506", "type": "monster"},
  "1507": {"name": "ID 1507", "type": "monster"},
  "1508": {"name": "ID 1508", "type": "monster"},
  "1509": {"name": "ID 1509", "type": "monster"},
  "1510": {"name": "ID 1510", "type": "monster"},
  "1511": {"name": "ID 1511", "type": "monster"},
  "1512": {"name": "ID 1512", "type": "monster"},
  "1513": {"name": "ID 1513", "type": "monster"},
  "1514": {"name": "ID 1514", "type": "monster"},
  "1515": {"name": "ID 1515", "type": "monster"},
  "1516": {"name": "ID 1516", "type": "monster"},
  "1517": {"name": "ID 1517", "type": "monster"},
  "1518": {"name": "ID 1518", "type": "monster"},
  "1519": {"name": "ID 1519", "type": "monster"},
  "1520": {"name": "ID 1520", "type": "monster"},
  "1521": {"name": "ID 1521", "type": "monster"},
  "1522": {"name": "ID 1522", "type": "monster"},
  "1523": {"name": "ID 1523", "type": "monster"},
  "1524": {"name": "ID 1524", "type": "monster"},
  "1525": {"name": "ID 1525", "type": "monster"},
  "1526": {"name": "ID 1526", "type": "monster"},
  "1527": {"name": "ID 1527", "type": "monster"},
  "1528": {"name": "ID 1528", "type": "monster"},
  "1529": {"name": "ID 1529", "type": "monster"},
  "1530": {"name": "ID 1530", "type": "monster"},
  "1531": {"name": "ID 1531", "type": "monster"},
  "1532": {"name": "ID 1532", "type": "monster"},
  "1533": {"name": "Parder", "type": "monster"},
  "1534": {"name": "Jungle Moa", "type": "monster"},
  "1535": {"name": "Two-Headed Turtle", "type": "monster"},
  "1536": {"name": "Giant Beaver", "type": "monster"},
  "1537": {"name": "Naga Archer", "type": "monster"},
  "1538": {"name": "Corrupt Naga", "type": "monster"},
  "1539": {"name": "Naga Warrior", "type": "monster"},
  "1540": {"name": "ID 1540", "type": "monster"},
  "1541": {"name": "ID 1541", "type": "monster"},
  "1542": {"name": "Timira the Many-Headed", "type": "monster"},
  "1543": {"name": "Rogue Naga", "type": "monster"},
  "1544": {"name": "ID 1544", "type": "monster"},
  "1545": {"name": "ID 1545", "type": "monster"},
  "1546": {"name": "Sulphider", "type": "monster"},
  "1547": {"name": "Sulphur Spouter", "type": "monster"},
  "1548": {"name": "Gore Horn", "type": "monster"},
  "1549": {"name": "Sabretooth", "type": "monster"},
  "1550": {"name": "Emerald Tortoise", "type": "monster"},
  "1551": {"name": "Undertaker", "type": "monster"},
  "1552": {"name": "Nighthunter", "type": "monster"},
  "1553": {"name": "Beast Hulking Prehemoth", "type": "monster"},
  "1554": {"name": "Stalking Stalk", "type": "monster"},
  "1555": {"name": "Fungosaurus", "type": "monster"},
  "1556": {"name": "Mantosaurus", "type": "monster"},
  "1557": {"name": "Headpecker", "type": "monster"},
  "1558": {"name": "Noxious Ripptor", "type": "monster"},
  "1559": {"name": "Gorerilla", "type": "monster"},
  "1560": {"name": "Shrieking Cry-Stal", "type": "monster"},
  "1561": {"name": "Mercurial Menace", "type": "monster"},
  "1562": {"name": "Foam Stalker", "type": "monster"},
  "1563": {"name": "ID 1563", "type": "monster"},
  "1564": {"name": "ID 1564", "type": "monster"},
  "1565": {"name": "Makara", "type": "monster"},
  "1566": {"name": "The Primal Menace", "type": "monster"},
  "1567": {"name": "Plunder Patriarch", "type": "monster"},
  "1568": {"name": "Fire-Fighter", "type": "male"},
  "1569": {"name": "Fire-Fighter", "type": "female"},
  "1570": {"name": "The End of Days", "type": "monster"},
  "1571": {"name": "ID 1571", "type": "monster"},
  "1572": {"name": "ID 1572", "type": "monster"},
  "1573": {"name": "ID 1573", "type": "monster"},
  "1574": {"name": "ID 1574", "type": "monster"},
  "1575": {"name": "Fencer", "type": "male"},
  "1576": {"name": "Fencer", "type": "female"},
  "1577": {"name": "ID 1577", "type": "monster"},
  "1578": {"name": "ID 1578", "type": "monster"},
  "1579": {"name": "ID 1579", "type": "monster"},
  "1580": {"name": "ID 1580", "type": "monster"},
  "1581": {"name": "Shadowlotus Disciple", "type": "male"},
  "1582": {"name": "Shadowlotus Disciple", "type": "female"},
  "1583": {"name": "ID 1583", "type": "monster"},
  "1584": {"name": "ID 1584", "type": "monster"},
  "1585": {"name": "ID 1585", "type": "monster"},
  "1586": {"name": "ID 1586", "type": "monster"},
  "1587": {"name": "Iks Aucar", "type": "monster"},
  "1588": {"name": "Iks Chuka", "type": "monster"},
  "1589": {"name": "Iks Pututu", "type": "monster"},
  "1590": {"name": "Iks Ahpututu", "type": "monster"},
  "1591": {"name": "Ahau", "type": "monster"},
  "1592": {"name": "Cursed Ape", "type": "monster"},
  "1593": {"name": "ID 1593", "type": "monster"},
  "1594": {"name": "ID 1594", "type": "monster"},
  "1595": {"name": "ID 1595", "type": "monster"},
  "1596": {"name": "ID 1596", "type": "monster"},
  "1597": {"name": "Ancient Aucar", "type": "male"},
  "1598": {"name": "Ancient Aucar", "type": "female"},
  "1599": {"name": "ID 1599", "type": "monster"},
  "1600": {"name": "The Monster", "type": "monster"},
  "1601": {"name": "Crape Man", "type": "monster"},
  "1602": {"name": "Liodile", "type": "monster"},
  "1603": {"name": "Boar Man", "type": "monster"},
  "1604": {"name": "Harpy", "type": "monster"},
  "1605": {"name": "Carnivostrich", "type": "monster"},
  "1606": {"name": "Rhindeer", "type": "monster"},
  "1607": {"name": "ID 1607", "type": "monster"},
  "1608": {"name": "ID 1608", "type": "monster"},
  "1609": {"name": "ID 1609", "type": "monster"},
  "1610": {"name": "ID 1610", "type": "monster"},
  "1611": {"name": "Doctor Marrow", "type": "monster"},
  "1612": {"name": "Frost Tracer", "type": "male"},
  "1613": {"name": "Frost Tracer", "type": "female"},
  "1614": {"name": "ID 1614", "type": "monster"},
  "1615": {"name": "ID 1615", "type": "monster"},
  "1616": {"name": "ID 1616", "type": "monster"},
  "1617": {"name": "ID 1617", "type": "monster"},
  "1618": {"name": "Armoured Archer", "type": "male"},
  "1619": {"name": "Armoured Archer", "type": "female"},
  "1620": {"name": "Mycobiontic Beetle", "type": "monster"},
  "1621": {"name": "Meandering Mushroom", "type": "monster"},
  "1622": {"name": "Darklight Construct", "type": "monster"},
  "1623": {"name": "Converter", "type": "monster"},
  "1624": {"name": "Darklight Matter", "type": "monster"},
  "1625": {"name": "Oozing Corpus", "type": "monster"},
  "1626": {"name": "Oozing Carcass", "type": "monster"},
  "1627": {"name": "Darklight Emitter", "type": "monster"},
  "1628": {"name": "Elder Bloodjaw", "type": "monster"},
  "1629": {"name": "ID 1629", "type": "monster"},
  "1630": {"name": "ID 1630", "type": "monster"},
  "1631": {"name": "ID 1631", "type": "monster"},
  "1632": {"name": "Foxmouse", "type": "monster"},
  "1633": {"name": "ID 1633", "type": "monster"},
  "1634": {"name": "ID 1634", "type": "monster"},
  "1635": {"name": "ID 1635", "type": "monster"},
  "1636": {"name": "ID 1636", "type": "monster"},
  "1637": {"name": "ID 1637", "type": "monster"},
  "1638": {"name": "ID 1638", "type": "monster"},
  "1639": {"name": "ID 1639", "type": "monster"},
  "1640": {"name": "ID 1640", "type": "monster"},
  "1641": {"name": "ID 1641", "type": "monster"},
  "1642": {"name": "ID 1642", "type": "monster"},
  "1643": {"name": "ID 1643", "type": "monster"},
  "1644": {"name": "ID 1644", "type": "monster"},
  "1645": {"name": "ID 1645", "type": "monster"},
  "1646": {"name": "Weretiger", "type": "monster"},
  "1647": {"name": "Feral Werecrocodile", "type": "monster"},
  "1648": {"name": "Cunning Werepanther", "type": "monster"},
  "1649": {"name": "White Tiger", "type": "monster"},
  "1650": {"name": "ID 1650", "type": "monster"},
  "1651": {"name": "ID 1651", "type": "monster"},
  "1652": {"name": "ID 1652", "type": "monster"},
  "1653": {"name": "ID 1653", "type": "monster"},
  "1654": {"name": "Bloated Man-Maggot", "type": "monster"},
  "1655": {"name": "Rotten Man-Maggot", "type": "monster"},
  "1656": {"name": "Walking Pillar", "type": "monster"},
  "1657": {"name": "Wandering Pillar", "type": "monster"},
  "1658": {"name": "Sopping Carcass", "type": "monster"},
  "1659": {"name": "Sopping Corpus", "type": "monster"},
  "1660": {"name": "Darklight Source", "type": "monster"},
  "1661": {"name": "Darklight Striker", "type": "monster"},
  "1662": {"name": "Decaying Defender", "type": "male"},
  "1663": {"name": "Decaying Defender", "type": "female"},
  "1664": {"name": "Murcion", "type": "monster"},
  "1665": {"name": "Ichgahal", "type": "monster"},
  "1666": {"name": "Chagorz", "type": "monster"},
  "1667": {"name": "ID 1667", "type": "monster"},
  "1668": {"name": "Vemiath", "type": "monster"},
  "1669": {"name": "Echo Of Ichgahal", "type": "monster"},
  "1670": {"name": "Echo Of Chagorz", "type": "monster"},
  "1671": {"name": "Bakragore", "type": "monster"},
  "1672": {"name": "ID 1672", "type": "monster"},
  "1673": {"name": "ID 1673", "type": "monster"},
  "1674": {"name": "ID 1674", "type": "monster"},
  "1675": {"name": "Darklight Evoker", "type": "male"},
  "1676": {"name": "Darklight Evoker", "type": "female"},
  "1677": {"name": "ID 1677", "type": "monster"},
  "1678": {"name": "ID 1678", "type": "monster"},
  "1679": {"name": "ID 1679", "type": "monster"},
  "1680": {"name": "Flamefury Mage", "type": "male"},
  "1681": {"name": "Flamefury Mage", "type": "female"},
  "1682": {"name": "ID 1682", "type": "monster"},
  "1683": {"name": "ID 1683", "type": "monster"},
  "1684": {"name": "ID 1684", "type": "monster"},
  "1685": {"name": "ID 1685", "type": "monster"},
  "1686": {"name": "ID 1686", "type": "monster"},
  "1687": {"name": "ID 1687", "type": "monster"},
  "1688": {"name": "ID 1688", "type": "monster"},
  "1689": {"name": "ID 1689", "type": "monster"},
  "1690": {"name": "ID 1690", "type": "monster"},
  "1691": {"name": "ID 1691", "type": "monster"},
  "1692": {"name": "ID 1692", "type": "monster"},
  "1693": {"name": "ID 1693", "type": "monster"},
  "1694": {"name": "ID 1694", "type": "monster"},
  "1695": {"name": "ID 1695", "type": "monster"},
  "1696": {"name": "ID 1696", "type": "monster"},
  "1697": {"name": "ID 1697", "type": "monster"},
  "1698": {"name": "ID 1698", "type": "monster"},
  "1699": {"name": "ID 1699", "type": "monster"},
  "1700": {"name": "ID 1700", "type": "monster"},
  "1701": {"name": "ID 1701", "type": "monster"},
  "1702": {"name": "Iks Yapunac", "type": "monster"},
  "1703": {"name": "ID 1703", "type": "monster"},
  "1704": {"name": "ID 1704", "type": "monster"},
  "1705": {"name": "ID 1705", "type": "monster"},
  "1706": {"name": "ID 1706", "type": "monster"},
  "1707": {"name": "Dragolisk", "type": "monster"},
  "1708": {"name": "Wardragon", "type": "monster"},
  "1709": {"name": "Mitmah Scout", "type": "monster"},
  "1710": {"name": "Mitmah Seer", "type": "monster"},
  "1711": {"name": "ID 1711", "type": "monster"},
  "1712": {"name": "Mega Dragon", "type": "monster"},
  "1713": {"name": "Doom Knight", "type": "male"},
  "1714": {"name": "Doom Knight", "type": "female"},
  "1715": {"name": "ID 1715", "type": "monster"},
  "1716": {"name": "Mitmah Vanguard", "type": "monster"},
  "1717": {"name": "Bulltaur Brute", "type": "monster"},
  "1718": {"name": "Bulltaur Alchemist", "type": "monster"},
  "1719": {"name": "ID 1719", "type": "monster"},
  "1720": {"name": "ID 1720", "type": "monster"},
  "1721": {"name": "ID 1721", "type": "monster"},
  "1722": {"name": "Draccoon Herald", "type": "male"},
  "1723": {"name": "Draccoon Herald", "type": "female"},
  "1724": {"name": "ID 1724", "type": "monster"},
  "1725": {"name": "Celestial Avenger", "type": "male"},
  "1726": {"name": "Celestial Avenger", "type": "female"},
  "1727": {"name": "ID 1727", "type": "monster"},
  "1728": {"name": "ID 1728", "type": "monster"},
  "1729": {"name": "ID 1729", "type": "monster"},
  "1730": {"name": "ID 1730", "type": "monster"},
  "1731": {"name": "ID 1731", "type": "monster"},
  "1732": {"name": "ID 1732", "type": "monster"},
  "1733": {"name": "Honey Elemental", "type": "monster"},
  "1734": {"name": "ID 1734", "type": "monster"},
  "1735": {"name": "ID 1735", "type": "monster"},
  "1736": {"name": "ID 1736", "type": "monster"},
  "1737": {"name": "Nibblemaw", "type": "monster"},
  "1738": {"name": "Gingerbread Man", "type": "monster"},
  "1739": {"name": "Candy Horror", "type": "monster"},
  "1740": {"name": "Goggle Cake", "type": "monster"},
  "1741": {"name": "Quara Looter", "type": "monster"},
  "1742": {"name": "ID 1742", "type": "monster"},
  "1743": {"name": "ID 1743", "type": "monster"},
  "1744": {"name": "ID 1744", "type": "monster"},
  "1745": {"name": "Blade Dancer", "type": "male"},
  "1746": {"name": "Blade Dancer", "type": "female"},
  "1747": {"name": "Angry Sugar Fairy", "type": "monster"},
  "1748": {"name": "ID 1748", "type": "monster"},
  "1749": {"name": "Candy Floss Elemental", "type": "monster"},
  "1750": {"name": "Truffle", "type": "monster"},
  "1751": {"name": "Truffle Cook", "type": "monster"},
  "1752": {"name": "ID 1752", "type": "monster"},
  "1753": {"name": "Sugar Cube", "type": "monster"},
  "1754": {"name": "Fruit Drop", "type": "monster"},
  "1755": {"name": "ID 1755", "type": "monster"},
  "1756": {"name": "Sugar Cube Worker", "type": "monster"},
  "1757": {"name": "Cream Blob", "type": "monster"},
  "1758": {"name": "Quara Plunderer", "type": "monster"},
  "1759": {"name": "Quara Raider", "type": "monster"},
  "1760": {"name": "Rootthing Nutshell", "type": "monster"},
  "1761": {"name": "ID 1761", "type": "monster"},
  "1762": {"name": "Rootthing Amber Shaper", "type": "monster"},
  "1763": {"name": "Rootthing Bug Tracker", "type": "monster"},
  "1764": {"name": "Sugar Daddy", "type": "monster"},
  "1765": {"name": "The Rootkraken", "type": "monster"},
  "1766": {"name": "ID 1766", "type": "monster"},
  "1767": {"name": "ID 1767", "type": "monster"},
  "1768": {"name": "ID 1768", "type": "monster"},
  "1769": {"name": "ID 1769", "type": "monster"},
  "1770": {"name": "ID 1770", "type": "monster"},
  "1771": {"name": "ID 1771", "type": "monster"},
  "1772": {"name": "ID 1772", "type": "monster"},
  "1773": {"name": "Mushroom", "type": "monster"},
  "1774": {"name": "Rootwalker", "type": "male"},
  "1775": {"name": "Rootwalker", "type": "female"},
  "1776": {"name": "Beekeeper", "type": "male"},
  "1777": {"name": "Beekeeper", "type": "female"},
  "1778": {"name": "ID 1778", "type": "monster"},
  "1779": {"name": "ID 1779", "type": "monster"},
  "1780": {"name": "ID 1780", "type": "monster"},
  "1781": {"name": "ID 1781", "type": "monster"},
  "1782": {"name": "ID 1782", "type": "monster"},
  "1783": {"name": "ID 1783", "type": "monster"},
  "1784": {"name": "ID 1784", "type": "monster"},
  "1785": {"name": "ID 1785", "type": "monster"},
  "1786": {"name": "ID 1786", "type": "monster"},
  "1787": {"name": "ID 1787", "type": "monster"},
  "1788": {"name": "ID 1788", "type": "monster"},
  "1789": {"name": "ID 1789", "type": "monster"},
  "1790": {"name": "ID 1790", "type": "monster"},
  "1791": {"name": "ID 1791", "type": "monster"},
  "1792": {"name": "Spellreaper Inferniarch", "type": "monster"},
  "1793": {"name": "Gralvalon", "type": "monster"},
  "1794": {"name": "Brinebrute Inferniarch", "type": "monster"},
  "1795": {"name": "Sineater Inferniarch", "type": "monster"},
  "1796": {"name": "Broodrider Inferniarch", "type": "monster"},
  "1797": {"name": "Gorger Inferniarch", "type": "monster"},
  "1798": {"name": "Arbaziloth", "type": "monster"},
  "1799": {"name": "ID 1799", "type": "monster"},
  "1800": {"name": "ID 1800", "type": "monster"},
  "1801": {"name": "ID 1801", "type": "monster"},
  "1802": {"name": "Weakened Arbaziloth", "type": "monster"},
  "1803": {"name": "ID 1803", "type": "monster"},
  "1804": {"name": "Imp Minion", "type": "monster"},
  "1805": {"name": "ID 1805", "type": "monster"},
  "1806": {"name": "ID 1806", "type": "monster"},
  "1807": {"name": "ID 1807", "type": "monster"},
  "1808": {"name": "Fiend Slayer", "type": "female"},
  "1809": {"name": "Fiend Slayer", "type": "male"},
  "1810": {"name": "ID 1810", "type": "monster"},
  "1811": {"name": "ID 1811", "type": "monster"},
  "1812": {"name": "ID 1812", "type": "monster"},
  "1813": {"name": "ID 1813", "type": "monster"},
  "1814": {"name": "Field Surgeon", "type": "male"},
  "1815": {"name": "Field Surgeon", "type": "female"},
  "1816": {"name": "ID 1816", "type": "monster"},
  "1817": {"name": "ID 1817", "type": "monster"},
  "1818": {"name": "Monk familiar", "type": "monster"},
  "1819": {"name": "ID 1819", "type": "monster"},
  "1820": {"name": "ID 1820", "type": "monster"},
  "1821": {"name": "ID 1821", "type": "monster"},
  "1822": {"name": "ID 1822", "type": "monster"},
  "1823": {"name": "ID 1823", "type": "monster"},
  "1824": {"name": "Monk", "type": "male"},
  "1825": {"name": "Monk", "type": "female"},
  "1826": {"name": "ID 1826", "type": "monster"},
  "1827": {"name": "ID 1827", "type": "monster"},
  "1828": {"name": "ID 1828", "type": "monster"},
  "1829": {"name": "ID 1829", "type": "monster"},
  "1830": {"name": "ID 1830", "type": "monster"},
  "1831": {"name": "Winged Druid", "type": "male"},
  "1832": {"name": "Winged Druid", "type": "female"},
  "1833": {"name": "ID 1833", "type": "monster"},
  "1834": {"name": "ID 1834", "type": "monster"},
  "1835": {"name": "ID 1835", "type": "monster"},
  "1836": {"name": "ID 1836", "type": "monster"},
  "1837": {"name": "Martial Artist", "type": "male"},
  "1838": {"name": "Martial Artist", "type": "female"},
  "1839": {"name": "ID 1839", "type": "monster"},
  "1840": {"name": "Flickering Spirit Elemental", "type": "monster"},
  "1841": {"name": "ID 1841", "type": "monster"},
  "1842": {"name": "ID 1842", "type": "monster"},
  "1843": {"name": "ID 1843", "type": "monster"},
  "1844": {"name": "ID 1844", "type": "monster"},
  "1845": {"name": "Necromancer", "type": "male"},
  "1846": {"name": "Necromancer", "type": "female"},
  "1847": {"name": "Crusader", "type": "monster"},
  "1848": {"name": "ID 1848", "type": "monster"},
  "1849": {"name": "Bluebeak", "type": "monster"},
  "1850": {"name": "Bramble Wyrmling", "type": "monster"},
  "1851": {"name": "ID 1851", "type": "monster"},
  "1852": {"name": "ID 1852", "type": "monster"},
  "1853": {"name": "ID 1853", "type": "monster"},
  "1854": {"name": "ID 1854", "type": "monster"},
  "1855": {"name": "ID 1855", "type": "monster"},
  "1856": {"name": "Headwalker", "type": "monster"},
  "1857": {"name": "Shell Drake", "type": "monster"},
  "1858": {"name": "Hawk Hopper", "type": "monster"},
  "1859": {"name": "Lion Hydra", "type": "monster"},
  "1860": {"name": "Illuminator", "type": "male"},
  "1861": {"name": "Illuminator", "type": "female"},
  "1862": {"name": "ID 1862", "type": "monster"},
  "1863": {"name": "ID 1863", "type": "monster"},
  "1864": {"name": "ID 1864", "type": "monster"},
  "1865": {"name": "ID 1865", "type": "monster"},
  "1866": {"name": "ID 1866", "type": "monster"},
  "1867": {"name": "ID 1867", "type": "monster"},
  "1868": {"name": "ID 1868", "type": "monster"},
  "1869": {"name": "ID 1869", "type": "monster"},
  "1870": {"name": "ID 1870", "type": "monster"},
  "1871": {"name": "ID 1871", "type": "monster"},
  "1872": {"name": "ID 1872", "type": "monster"},
  "1873": {"name": "ID 1873", "type": "monster"},
  "1874": {"name": "Bat Knight", "type": "male"},
  "1875": {"name": "Bat Knight", "type": "female"}
};
